# M6 W6 v2 retrieval evaluation

This notebook evaluates the three-book, 5,976-chunk v2 handoff with the shared
project retriever. It does not contain a second BM25, dense-search, or RRF
implementation.

Protocol:

- Development: BM25 plus nine dense models, each with Dense and six Hybrid weights
  (64 configurations).
- Candidate depth: project default `rrf_input_top_k=20`.
- Test: only the predeclared BGE-M3 Hybrid configuration
  (Dense 0.10 / BM25 0.90). BM25 is not rerun on Test, and Test is not used for selection.
- All result tables displayed below are loaded from generated CSV files.

## 1. Configuration and reproducibility

Inputs must be supplied through `CS30_M6_*` environment variables or placed in
`eval_inputs/m6_v2/`. There is deliberately no Desktop fallback. Large indexes
remain under ignored `artifacts/`; the small manifest and summary CSVs are written
to `docs/results/m6_w6_v2/` for review.

In [1]:
from __future__ import annotations

import collections
import gc
import hashlib
import json
import math
import os
import re
import sys
import zipfile
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd


def find_project_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "pyproject.toml").is_file() and (candidate / "src" / "cs30").is_dir():
            return candidate
    raise FileNotFoundError("Run this notebook from the cs30-personalised-rag checkout.")


PROJECT_ROOT = find_project_root(Path.cwd().resolve())
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from cs30.config import AppConfig, RetrievalConfig  # noqa: E402
from cs30.contracts import RetrievalMode  # noqa: E402
from cs30.evaluation.manifest import capture_git_state  # noqa: E402
from cs30.pipeline import build_real_retrieval_deps  # noqa: E402
from cs30.retrieval.v2_adapter import materialise_v2_retrieval_view  # noqa: E402

INPUT_DIR = Path(
    os.getenv("CS30_M6_INPUT_DIR", PROJECT_ROOT / "eval_inputs" / "m6_v2")
).expanduser()


def resolve_input(env_name: str, filename: str) -> Path:
    configured = os.getenv(env_name)
    candidate = Path(configured).expanduser() if configured else INPUT_DIR / filename
    if not candidate.is_file():
        raise FileNotFoundError(
            f"Missing {filename}. Set {env_name} or place it under {INPUT_DIR}."
        )
    return candidate.resolve()


CORPUS_ZIP = resolve_input(
    "CS30_M6_CORPUS_ZIP",
    "v2_structure_aware_corpus_3book_dev_main_3553825.zip",
)
M5_ZIP = resolve_input(
    "CS30_M6_INDEX_ZIP",
    "M5_v2_candidate_indexes_2026-10-09.zip",
)
INTEGRATED_GOLD = resolve_input(
    "CS30_M6_GOLD",
    "gold_v0_1_1_integrated.jsonl",
)

WORK_DIR = Path(
    os.getenv(
        "CS30_M6_WORK_DIR",
        PROJECT_ROOT / "artifacts" / "m6_w6_retrieval",
    )
).expanduser()
RESULT_DIR = Path(
    os.getenv(
        "CS30_M6_RESULT_DIR",
        PROJECT_ROOT / "docs" / "results" / "m6_w6_v2",
    )
).expanduser()
RUN_EXPENSIVE = os.getenv("CS30_M6_RUN_MODELS", "0") == "1"
DEVICE = os.getenv("CS30_M6_DEVICE", "cuda")

TOP_K = (1, 3, 5, 10)
FINAL_TOP_K = max(TOP_K)
RRF_K = 60
RRF_INPUT_TOP_K = 20
HYBRID_WEIGHTS = (
    (0.95, 0.05),
    (0.90, 0.10),
    (0.80, 0.20),
    (0.75, 0.25),
    (0.50, 0.50),
    (0.25, 0.75),
)  # (BM25, Dense)
FROZEN = {
    "model": "bge_m3",
    "mode": "hybrid_d0.10_b0.90",
    "dense_weight": 0.10,
    "bm25_weight": 0.90,
    "declared_before_test": True,
}

print("Repository:", PROJECT_ROOT)
print("Inputs:", INPUT_DIR)
print("Results:", RESULT_DIR)
print("Expensive run:", RUN_EXPENSIVE, "device:", DEVICE)

Repository: D:\capstone\cs30-personalised-rag
Inputs: D:\capstone\cs30-personalised-rag\eval_inputs\m6_v2
Results: D:\capstone\cs30-personalised-rag\docs\results\m6_w6_v2
Expensive run: True device: cuda

## 2. Model registry, pinned revisions, and input validation

In [2]:
MODEL_SPECS = {
    "minilm": {
        "model": "sentence-transformers/all-MiniLM-L6-v2",
        "revision": "1110a243fdf4706b3f48f1d95db1a4f5529b4d41",
        "dimension": 384,
        "batch": 64,
    },
    "mpnet": {
        "model": "sentence-transformers/all-mpnet-base-v2",
        "revision": "e8c3b32edf5434bc2275fc9bab85f82640a19130",
        "dimension": 768,
        "batch": 32,
    },
    "e5_base": {
        "model": "intfloat/e5-base-v2",
        "revision": "f52bf8ec8c7124536f0efb74aca902b2995e5bcd",
        "dimension": 768,
        "batch": 32,
        "query_instruction": "query: ",
        "document_prefix": "passage: ",
    },
    "bge_base": {
        "model": "BAAI/bge-base-en-v1.5",
        "revision": "a5beb1e3e68b9ab74eb54cfd186867f64f240e1a",
        "dimension": 768,
        "batch": 32,
        "query_instruction": "Represent this sentence for searching relevant passages: ",
    },
    "jina": {
        "model": "jinaai/jina-embeddings-v2-small-en",
        "revision": "44e7d1d6caec8c883c2d4b207588504d519788d0",
        "dimension": 512,
        "batch": 16,
        "trust_remote_code": True,
    },
    "gte_modernbert": {
        "model": "Alibaba-NLP/gte-modernbert-base",
        "revision": "e7f32e3c00f91d699e8c43b53106206bcc72bb22",
        "dimension": 768,
        "batch": 4,
        "trust_remote_code": True,
        "m5_path": "gte-modernbert",
    },
    "nomic": {
        "model": "nomic-ai/nomic-embed-text-v1.5",
        "revision": "e9b6763023c676ca8431644204f50c2b100d9aab",
        "dimension": 768,
        "batch": 8,
        "trust_remote_code": True,
        "query_instruction": "search_query: ",
        "document_prefix": "search_document: ",
    },
    "bge_m3": {
        "model": "BAAI/bge-m3",
        "revision": "5617a9f61b028005a4858fdac845db406aefb181",
        "dimension": 1024,
        "batch": 4,
        "m5_path": "bge-m3",
    },
    "qwen3": {
        "model": "Qwen/Qwen3-Embedding-0.6B",
        "revision": "97b0c614be4d77ee51c0cef4e5f07c00f9eb65b3",
        "dimension": 1024,
        "batch": 2,
        "m5_path": "qwen3-embedding",
        "query_prompt_name": "query",
    },
}
for spec in MODEL_SPECS.values():
    spec.setdefault("query_instruction", "")
    spec.setdefault("query_prompt_name", None)
    spec.setdefault("document_prefix", "")
    spec.setdefault("trust_remote_code", False)
    assert re.fullmatch(r"[0-9a-f]{40}", spec["revision"])


def sha256(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def read_jsonl(data: bytes) -> list[dict]:
    text = data.decode("utf-8-sig")
    return [json.loads(line) for line in text.splitlines() if line.strip()]


with zipfile.ZipFile(CORPUS_ZIP) as archive:
    corpus_bytes = archive.read("records.jsonl")
    corpus_manifest = json.loads(archive.read("manifest.json"))
    chunks = read_jsonl(corpus_bytes)
    for line in archive.read("SHA256SUMS.txt").decode("utf-8").splitlines():
        expected, filename = line.split(None, 1)
        assert hashlib.sha256(archive.read(filename.strip())).hexdigest() == expected

gold_bytes = INTEGRATED_GOLD.read_bytes()
gold = read_jsonl(gold_bytes)
ordered_chunk_ids = [row["chunk_id"] for row in chunks]
by_chunk = {row["chunk_id"]: row for row in chunks}

assert sha256(corpus_bytes) == corpus_manifest["corpus_hash"]
assert len(chunks) == corpus_manifest["record_count"] == 5976
assert len(ordered_chunk_ids) == len(set(ordered_chunk_ids))
assert len(gold) == 188
assert len({row["question_id"] for row in gold}) == 188
assert all(row["answerable"] is True for row in gold)
assert {row["corpus_version"] for row in gold} == {corpus_manifest["corpus_version"]}

WORKING_SPLIT_POLICY = {
    "pending": "dev",
    "proposed_test": "test",
    "dev": "dev",
    "test": "test",
}
dev_gold = [row for row in gold if WORKING_SPLIT_POLICY.get(row["split"]) == "dev"]
test_gold = [row for row in gold if WORKING_SPLIT_POLICY.get(row["split"]) == "test"]
assert len(dev_gold) == 162 and len(test_gold) == 26
assert not ({row["question_id"] for row in dev_gold} & {row["question_id"] for row in test_gold})

print("Models:", len(MODEL_SPECS))
print("Corpus chunks:", len(chunks))
print("Working Dev/Test:", len(dev_gold), len(test_gold))

Models: 9
Corpus chunks: 5976
Working Dev/Test: 162 26

## 3. Bind Gold evidence spans to v2 chunk IDs

In [3]:
def normalized(text: str) -> str:
    return " ".join(text.casefold().split())


block_to_chunks = collections.defaultdict(set)
for chunk in chunks:
    for span in chunk["spans"]:
        block_to_chunks[span["block_id"]].add(chunk["chunk_id"])

binding_rows = []
gold_paths = {}
for question in gold:
    paths = []
    for group in question["gold_core_evidence_sets"]:
        mapped = []
        for span in group:
            candidates = block_to_chunks.get(span.get("block_id"), set())
            assert len(candidates) == 1, (question["question_id"], span.get("span_id"))
            chunk_id = next(iter(candidates))
            chunk = by_chunk[chunk_id]
            assert str(chunk["chapter_id"]) == str(span["chapter_id"])
            assert normalized(span["verbatim_text"]) in normalized(chunk["text"])
            mapped.append(chunk_id)
            binding_rows.append(
                {
                    "question_id": question["question_id"],
                    "span_id": span["span_id"],
                    "block_id": span["block_id"],
                    "chunk_id": chunk_id,
                    "textbook_id": chunk["textbook_id"],
                    "method": "unique_block_id+chapter+verbatim",
                }
            )
        paths.append(frozenset(mapped))
    assert paths
    gold_paths[question["question_id"]] = paths

binding_bytes = ("\n".join(json.dumps(row, sort_keys=True) for row in binding_rows) + "\n").encode()
print("Bound Gold spans:", len(binding_rows), "SHA-256:", sha256(binding_bytes))

Bound Gold spans: 195 SHA-256: sha256:98f70f3eee137f1ccd7252b14e55ed3bdac76a75ac5b0e0141ecc5b2dd68991f

## 4. Validate M5 candidates and prepare project-retriever views

The adapter validates v2 identity and chunk order, then writes the v1 compatibility
layout consumed by `build_real_retrieval_deps`. It does not implement retrieval.
Locally built indexes use the same pinned revisions and corpus order.

In [4]:
M5_ARTIFACTS = {}
M5_INDEX_MEMBERS = {}
with zipfile.ZipFile(M5_ZIP) as archive:
    members = {name.replace("\\", "/"): name for name in archive.namelist()}
    assert len(members) == len(archive.namelist())
    for key, spec in MODEL_SPECS.items():
        if "m5_path" not in spec:
            continue
        prefix = f"v2-m5-candidates/{spec['m5_path']}/"
        artifact = json.loads(archive.read(members[prefix + "artifact.json"]))
        ids_bytes = archive.read(members[prefix + "index/chunk_ids.json"])
        index_member = members[prefix + "index/index.faiss"]
        index_bytes = archive.read(index_member)
        assert artifact["corpus_hash"] == corpus_manifest["corpus_hash"]
        assert artifact["manifest_hash"] == corpus_manifest["manifest_hash"]
        assert artifact["chunk_config_hash"] == corpus_manifest["chunk_config_hash"]
        assert artifact["chunk_ids"] == ordered_chunk_ids
        assert json.loads(ids_bytes) == ordered_chunk_ids
        assert sha256(ids_bytes) == artifact["metadata"]["chunk_ids_sha256"]
        assert sha256(index_bytes) == artifact["metadata"]["index_sha256"]
        assert artifact["embedding_model"] == spec["model"]
        assert artifact["embedding_revision"] == spec["revision"]
        assert artifact["embedding_dimension"] == spec["dimension"]
        assert artifact["similarity_metric"] == "inner_product"
        assert artifact["normalise_embeddings"] is True
        M5_ARTIFACTS[key] = artifact
        M5_INDEX_MEMBERS[key] = index_member

display(
    pd.DataFrame(
        [
            {
                "model_key": key,
                "embedding_model": artifact["embedding_model"],
                "revision": artifact["embedding_revision"],
                "dimension": artifact["embedding_dimension"],
            }
            for key, artifact in M5_ARTIFACTS.items()
        ]
    )
)

,model_key,embedding_model,revision,dimension
0,gte_modernbert,Alibaba-NLP/gte-modernbert-base,e7f32e3c00f91d699e8c43b53106206bcc72bb22,768
1,bge_m3,BAAI/bge-m3,5617a9f61b028005a4858fdac845db406aefb181,1024
2,qwen3,Qwen/Qwen3-Embedding-0.6B,97b0c614be4d77ee51c0cef4e5f07c00f9eb65b3,1024

In [5]:
def local_v2_artifact(key: str, index_path: Path) -> dict:
    spec = MODEL_SPECS[key]
    return {
        "schema_version": "2.0",
        "artifact_id": f"m6-local-{key}-{corpus_manifest['corpus_hash'][-12:]}",
        "index_type": "faiss.IndexFlatIP",
        "corpus_hash": corpus_manifest["corpus_hash"],
        "chunk_config_hash": corpus_manifest["chunk_config_hash"],
        "chunk_count": len(chunks),
        "chunk_ids": ordered_chunk_ids,
        "embedding_model": spec["model"],
        "embedding_revision": spec["revision"],
        "embedding_dimension": spec["dimension"],
        "similarity_metric": "inner_product",
        "normalise_embeddings": True,
        "index_version": "m6-local-faiss-flat-ip-1",
        "metadata": {"index_sha256": sha256(index_path.read_bytes())},
    }


def ensure_raw_index(key: str) -> tuple[dict, Path]:
    spec = MODEL_SPECS[key]
    raw_dir = WORK_DIR / "raw_indexes" / key
    raw_dir.mkdir(parents=True, exist_ok=True)
    index_path = raw_dir / "index.faiss"
    local_manifest = raw_dir / "build.json"

    if key in M5_ARTIFACTS:
        expected_hash = M5_ARTIFACTS[key]["metadata"]["index_sha256"]
        if not index_path.is_file() or sha256(index_path.read_bytes()) != expected_hash:
            with zipfile.ZipFile(M5_ZIP) as archive:
                index_path.write_bytes(archive.read(M5_INDEX_MEMBERS[key]))
        return M5_ARTIFACTS[key], index_path

    expected = {
        "corpus_hash": corpus_manifest["corpus_hash"],
        "embedding_model": spec["model"],
        "embedding_revision": spec["revision"],
        "dimension": spec["dimension"],
        "document_prefix": spec["document_prefix"],
        "normalise_embeddings": True,
    }
    reusable = False
    if local_manifest.is_file() and index_path.is_file():
        saved = json.loads(local_manifest.read_text(encoding="utf-8"))
        reusable = all(saved.get(name) == value for name, value in expected.items())
        reusable = reusable and saved.get("index_sha256") == sha256(index_path.read_bytes())
    if not reusable:
        import faiss
        from sentence_transformers import SentenceTransformer

        model = SentenceTransformer(
            spec["model"],
            revision=spec["revision"],
            device=DEVICE,
            trust_remote_code=spec["trust_remote_code"],
        )
        texts = [spec["document_prefix"] + (row.get("embed_text") or row["text"]) for row in chunks]
        vectors = model.encode(
            texts,
            batch_size=spec["batch"],
            normalize_embeddings=True,
            convert_to_numpy=True,
            show_progress_bar=True,
        ).astype("float32")
        assert vectors.shape == (len(chunks), spec["dimension"])
        index = faiss.IndexFlatIP(spec["dimension"])
        index.add(vectors)
        faiss.write_index(index, str(index_path))
        saved = {
            **expected,
            "index_sha256": sha256(index_path.read_bytes()),
            "built_at_utc": datetime.now(UTC).isoformat(),
        }
        local_manifest.write_text(json.dumps(saved, indent=2) + "\n", encoding="utf-8")
        del model, vectors, index
        gc.collect()
    return local_v2_artifact(key, index_path), index_path


def prepare_retrieval_view(key: str) -> tuple[Path, dict]:
    artifact, index_path = ensure_raw_index(key)
    view_dir = WORK_DIR / "project_views" / key
    spec = MODEL_SPECS[key]
    materialise_v2_retrieval_view(
        v2_artifact=artifact,
        records=chunks,
        index_source=index_path,
        output_dir=view_dir,
        query_instruction=spec["query_instruction"],
        query_prompt_name=spec["query_prompt_name"],
    )
    return view_dir, artifact

## 5. Truncation diagnostics

In [6]:
def truncation_diagnostic(key: str) -> dict:
    from sentence_transformers import SentenceTransformer

    spec = MODEL_SPECS[key]
    model = SentenceTransformer(
        spec["model"],
        revision=spec["revision"],
        device=DEVICE,
        trust_remote_code=spec["trust_remote_code"],
    )
    max_length = int(model.max_seq_length)
    truncated = 0
    maximum_observed = 0
    batch_size = 128
    texts = [spec["document_prefix"] + (row.get("embed_text") or row["text"]) for row in chunks]
    for start in range(0, len(texts), batch_size):
        encoded = model.tokenizer(
            texts[start : start + batch_size],
            add_special_tokens=True,
            truncation=False,
        )["input_ids"]
        lengths = [len(token_ids) for token_ids in encoded]
        maximum_observed = max(maximum_observed, max(lengths, default=0))
        truncated += sum(length > max_length for length in lengths)
    row = {
        "model": key,
        "embedding_model": spec["model"],
        "embedding_revision": spec["revision"],
        "max_input_tokens": max_length,
        "maximum_observed_tokens": maximum_observed,
        "chunk_count": len(texts),
        "truncated_chunk_count": truncated,
        "truncated_chunk_rate": truncated / len(texts),
    }
    del model
    gc.collect()
    return row


if RUN_EXPENSIVE:
    truncation_summary = pd.DataFrame([truncation_diagnostic(key) for key in MODEL_SPECS])
    RESULT_DIR.mkdir(parents=True, exist_ok=True)
    truncation_summary.to_csv(RESULT_DIR / "truncation_diagnostics.csv", index=False)
    display(truncation_summary)
else:
    print("Truncation diagnostics run with CS30_M6_RUN_MODELS=1.")

E:\Sydney\vscode\w5_20_m6_golden_evidence\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Token indices sequence length is longer than the specified maximum sequence length for this model (374 > 256). Running this sequence through the model will result in indexing errors

Token indices sequence length is longer than the specified maximum sequence length for this model (439 > 384). Running this sequence through the model will result in indexing errors

Token indices sequence length is longer than the specified maximum sequence length for this model (518 > 512). Running this sequence through the model will result in indexing errors

Token indices sequence length is longer than the specified maximum sequence length for this model (516 > 512). Running this sequence through the model will result in indexing errors

<All keys matched successfully>

,model,embedding_model,embedding_revision,max_input_tokens,maximum_observed_tokens,chunk_count,truncated_chunk_count,truncated_chunk_rate
0,minilm,sentence-transformers/all-MiniLM-L6-v2,1110a243fdf4706b3f48f1d95db1a4f5529b4d41,256,697,5976,3742,0.626171
1,mpnet,sentence-transformers/all-mpnet-base-v2,e8c3b32edf5434bc2275fc9bab85f82640a19130,384,697,5976,2873,0.480756
2,e5_base,intfloat/e5-base-v2,f52bf8ec8c7124536f0efb74aca902b2995e5bcd,512,699,5976,943,0.157798
3,bge_base,BAAI/bge-base-en-v1.5,a5beb1e3e68b9ab74eb54cfd186867f64f240e1a,512,697,5976,885,0.148092
4,jina,jinaai/jina-embeddings-v2-small-en,44e7d1d6caec8c883c2d4b207588504d519788d0,8192,697,5976,0,0.000000
5,gte_modernbert,Alibaba-NLP/gte-modernbert-base,e7f32e3c00f91d699e8c43b53106206bcc72bb22,8192,806,5976,0,0.000000
6,nomic,nomic-ai/nomic-embed-text-v1.5,e9b6763023c676ca8431644204f50c2b100d9aab,8192,701,5976,0,0.000000
7,bge_m3,BAAI/bge-m3,5617a9f61b028005a4858fdac845db406aefb181,8192,828,5976,0,0.000000
8,qwen3,Qwen/Qwen3-Embedding-0.6B,97b0c614be4d77ee51c0cef4e5f07c00f9eb65b3,32768,992,5976,0,0.000000

## 6. Shared project retriever

Every measured result below comes from a retriever returned by
`build_real_retrieval_deps`. Project tokenization, query-side stopwords, Dense
normalization, candidate depth, and weighted RRF therefore stay aligned with the
application.

In [7]:
def build_project_retriever(
    key: str,
    mode: RetrievalMode,
    *,
    dense_weight: float = 0.10,
    bm25_weight: float = 0.90,
):
    view_dir, artifact = prepare_retrieval_view(key)
    spec = MODEL_SPECS[key]
    config = AppConfig(
        fixture_mode=False,
        retrieval=RetrievalConfig(
            mode=mode,
            index_dir=str(view_dir),
            rrf_k=RRF_K,
            rrf_input_top_k=RRF_INPUT_TOP_K,
            rrf_dense_weight=dense_weight,
            rrf_bm25_weight=bm25_weight,
            bm25_stopwords=True,
            expected_embedding_model=spec["model"],
            expected_embedding_revision=spec["revision"],
            embedding_trust_remote_code=spec["trust_remote_code"],
            query_prompt_name=spec["query_prompt_name"],
        ),
    )
    return build_real_retrieval_deps(config).retriever, artifact


def hit_pairs(result) -> list[tuple[str, float]]:
    return [(hit.chunk_id, float(hit.score)) for hit in result.hits]


def candidate_rows(question: dict, model: str, mode: str, result) -> list[dict]:
    rows = []
    for hit in result.hits:
        chunk = by_chunk[hit.chunk_id]
        rows.append(
            {
                "question_id": question["question_id"],
                "model": model,
                "mode": mode,
                "rank": hit.rank,
                "chunk_id": hit.chunk_id,
                "score": float(hit.score),
                "query": question["question"],
                "textbook_id": chunk["textbook_id"],
                "provider": chunk["provider"],
                "source_locator": chunk["source_locator"],
            }
        )
    return rows

## 7. Evidence metrics

In [8]:
def score_one(
    question: dict,
    hits: list[tuple[str, float]],
    model_key: str,
    mode: str,
    bm25_weight=None,
    dense_weight=None,
) -> dict:
    ids = [chunk_id for chunk_id, _ in hits]
    assert len(ids) == len(set(ids))
    paths = gold_paths[question["question_id"]]
    relevant = set().union(*paths)
    rank = {chunk_id: position for position, chunk_id in enumerate(ids, 1)}
    first_rank = min((rank[cid] for cid in relevant if cid in rank), default=None)
    complete_rank = min(
        (max((rank.get(cid, math.inf) for cid in path), default=math.inf) for path in paths),
        default=math.inf,
    )
    complete_rank = None if math.isinf(complete_rank) else int(complete_rank)
    source_ids = {by_chunk[cid]["textbook_id"] for cid in relevant}
    providers = {by_chunk[cid]["provider"] for cid in relevant}
    row = {
        "question_id": question["question_id"],
        "evaluation_split": WORKING_SPLIT_POLICY[question["split"]],
        "annotation_status": question["annotation_status"],
        "model": model_key,
        "mode": mode,
        "bm25_weight": bm25_weight,
        "dense_weight": dense_weight,
        "scope": "cross_textbook" if len(source_ids) > 1 else "single_source",
        "provider_scope": "cross_provider" if len(providers) > 1 else "single_provider",
        "gold_textbook": "+".join(sorted(source_ids)),
        "gold_provider": "+".join(sorted(providers)),
        "first_relevant_rank": first_rank,
        "complete_evidence_rank": complete_rank,
        "mrr": 0.0 if first_rank is None else 1 / first_rank,
        "complete_evidence_mrr": 0.0 if complete_rank is None else 1 / complete_rank,
        "returned_count": len(hits),
        "empty_retrieval": int(not hits),
        "ranked_chunk_ids": ids,
    }
    for k in TOP_K:
        top = set(ids[:k])
        row[f"hit_at_{k}"] = int(bool(top & relevant))
        row[f"complete_hit_at_{k}"] = int(any(path <= top for path in paths))
        row[f"evidence_recall_at_{k}"] = max(
            (len(path & top) / len(path) for path in paths),
            default=0.0,
        )
        row[f"core_precision_at_{k}"] = len(top & relevant) / len(top) if top else None
        row[f"no_relevant_hit_at_{k}"] = int(not (top & relevant))
    return row


def summarize(rows: list[dict]) -> pd.DataFrame:
    frame = pd.DataFrame(rows)
    frame["run_name"] = frame["model"] + "_" + frame["mode"]
    for k in TOP_K:
        frame[f"context_noise_rate_at_{k}"] = 1 - frame[f"core_precision_at_{k}"]
        frame[f"returned_count_at_{k}"] = frame["returned_count"].clip(upper=k)
        frame[f"empty_retrieval_rate_at_{k}"] = frame[f"returned_count_at_{k}"].eq(0)
    metrics = ["mrr", "complete_evidence_mrr", "returned_count", "empty_retrieval"]
    metrics += [
        f"{metric}_at_{k}"
        for metric in (
            "hit",
            "complete_hit",
            "evidence_recall",
            "core_precision",
            "context_noise_rate",
            "no_relevant_hit",
            "returned_count",
            "empty_retrieval_rate",
        )
        for k in TOP_K
    ]
    groups = ["run_name", "model", "mode", "dense_weight", "bm25_weight"]
    grouped = frame.groupby(groups, dropna=False)
    return (
        grouped.size()
        .rename("question_count")
        .to_frame()
        .join(grouped[metrics].mean())
        .reset_index()
    )


def sort_summary(frame: pd.DataFrame) -> pd.DataFrame:
    return frame.sort_values(
        ["complete_hit_at_5", "mrr", "run_name"],
        ascending=[False, False, True],
    ).reset_index(drop=True)

## 8. Development sweep: 64 configurations

In [9]:
def evaluate_dev() -> tuple[list[dict], list[dict], dict]:
    rows = []
    candidates = []
    provenance = {}

    baseline, _ = build_project_retriever("bge_m3", RetrievalMode.BM25)
    for question in dev_gold:
        result = baseline.retrieve(question["question"], FINAL_TOP_K)
        rows.append(score_one(question, hit_pairs(result), "bm25", "bm25"))
        candidates.extend(candidate_rows(question, "bm25", "bm25", result))
    del baseline

    for key in MODEL_SPECS:
        print("Dev:", key, flush=True)
        hybrid, artifact = build_project_retriever(key, RetrievalMode.HYBRID)
        provenance[key] = artifact
        for question in dev_gold:
            dense_result = hybrid.dense.retrieve(question["question"], FINAL_TOP_K)
            rows.append(score_one(question, hit_pairs(dense_result), key, "dense"))
            candidates.extend(candidate_rows(question, key, "dense", dense_result))
            for bm25_weight, dense_weight in HYBRID_WEIGHTS:
                hybrid.bm25_weight = bm25_weight
                hybrid.dense_weight = dense_weight
                mode = f"hybrid_d{dense_weight:.2f}_b{bm25_weight:.2f}"
                result = hybrid.retrieve(question["question"], FINAL_TOP_K)
                rows.append(
                    score_one(
                        question,
                        hit_pairs(result),
                        key,
                        mode,
                        bm25_weight,
                        dense_weight,
                    )
                )
                candidates.extend(candidate_rows(question, key, mode, result))
        del hybrid
        gc.collect()
    return rows, candidates, provenance


if RUN_EXPENSIVE:
    WORK_DIR.mkdir(parents=True, exist_ok=True)
    RESULT_DIR.mkdir(parents=True, exist_ok=True)
    dev_rows, dev_candidates, index_provenance = evaluate_dev()
    assert len(dev_rows) == len(dev_gold) * 64
    dev_summary = sort_summary(summarize(dev_rows))
    dev_summary.to_csv(RESULT_DIR / "dev_summary.csv", index=False)
    display(dev_summary)
else:
    dev_rows = dev_candidates = []
    index_provenance = {}
    print("Dev sweep skipped. Set CS30_M6_RUN_MODELS=1 to run it.")

Dev: minilm

Batches:   0%|          | 0/94 [00:00<?, ?it/s]

Batches:   1%|          | 1/94 [00:00<00:56,  1.64it/s]

Batches:   3%|▎         | 3/94 [00:00<00:20,  4.35it/s]

Batches:   4%|▍         | 4/94 [00:00<00:16,  5.34it/s]

Batches:   6%|▋         | 6/94 [00:01<00:12,  6.93it/s]

Batches:   9%|▊         | 8/94 [00:01<00:10,  7.94it/s]

Batches:  11%|█         | 10/94 [00:01<00:09,  8.61it/s]

Batches:  13%|█▎        | 12/94 [00:01<00:09,  9.10it/s]

Batches:  15%|█▍        | 14/94 [00:01<00:08,  9.42it/s]

Batches:  17%|█▋        | 16/94 [00:02<00:07,  9.82it/s]

Batches:  19%|█▉        | 18/94 [00:02<00:07,  9.90it/s]

Batches:  21%|██▏       | 20/94 [00:02<00:07, 10.10it/s]

Batches:  23%|██▎       | 22/94 [00:02<00:07, 10.26it/s]

Batches:  26%|██▌       | 24/94 [00:02<00:06, 10.22it/s]

Batches:  28%|██▊       | 26/94 [00:03<00:06, 10.21it/s]

Batches:  30%|██▉       | 28/94 [00:03<00:06, 10.27it/s]

Batches:  32%|███▏      | 30/94 [00:03<00:06, 10.43it/s]

Batches:  34%|███▍      | 32/94 [00:03<00:05, 10.47it/s]

Batches:  36%|███▌      | 34/94 [00:03<00:05, 10.49it/s]

Batches:  38%|███▊      | 36/94 [00:04<00:05, 10.56it/s]

Batches:  40%|████      | 38/94 [00:04<00:05, 10.28it/s]

Batches:  43%|████▎     | 40/94 [00:04<00:05, 10.34it/s]

Batches:  45%|████▍     | 42/94 [00:04<00:05, 10.27it/s]

Batches:  47%|████▋     | 44/94 [00:04<00:04, 10.48it/s]

Batches:  49%|████▉     | 46/94 [00:04<00:04, 10.39it/s]

Batches:  51%|█████     | 48/94 [00:05<00:04, 10.32it/s]

Batches:  53%|█████▎    | 50/94 [00:05<00:04, 10.25it/s]

Batches:  55%|█████▌    | 52/94 [00:05<00:04,  9.16it/s]

Batches:  57%|█████▋    | 54/94 [00:05<00:04,  9.56it/s]

Batches:  60%|█████▉    | 56/94 [00:06<00:03,  9.78it/s]

Batches:  62%|██████▏   | 58/94 [00:06<00:03, 10.03it/s]

Batches:  64%|██████▍   | 60/94 [00:06<00:03, 10.13it/s]

Batches:  66%|██████▌   | 62/94 [00:06<00:03, 10.25it/s]

Batches:  68%|██████▊   | 64/94 [00:06<00:02, 10.33it/s]

Batches:  70%|███████   | 66/94 [00:06<00:02, 10.41it/s]

Batches:  72%|███████▏  | 68/94 [00:07<00:02, 10.53it/s]

Batches:  74%|███████▍  | 70/94 [00:07<00:02, 10.66it/s]

Batches:  77%|███████▋  | 72/94 [00:07<00:02, 10.79it/s]

Batches:  79%|███████▊  | 74/94 [00:07<00:01, 11.10it/s]

Batches:  81%|████████  | 76/94 [00:07<00:01, 11.44it/s]

Batches:  83%|████████▎ | 78/94 [00:07<00:01, 12.54it/s]

Batches:  85%|████████▌ | 80/94 [00:08<00:01, 13.53it/s]

Batches:  87%|████████▋ | 82/94 [00:08<00:00, 14.86it/s]

Batches:  90%|█████████ | 85/94 [00:08<00:00, 18.09it/s]

Batches:  94%|█████████▎| 88/94 [00:08<00:00, 20.77it/s]

Batches:  99%|█████████▉| 93/94 [00:08<00:00, 28.11it/s]

Batches: 100%|██████████| 94/94 [00:08<00:00, 11.00it/s]

Dev: mpnet

Batches:   0%|          | 0/187 [00:00<?, ?it/s]

Batches:   1%|          | 1/187 [00:00<01:31,  2.04it/s]

Batches:   1%|          | 2/187 [00:00<01:25,  2.17it/s]

Batches:   2%|▏         | 3/187 [00:01<01:22,  2.22it/s]

Batches:   2%|▏         | 4/187 [00:01<01:22,  2.22it/s]

Batches:   3%|▎         | 5/187 [00:02<01:22,  2.22it/s]

Batches:   3%|▎         | 6/187 [00:02<01:22,  2.20it/s]

Batches:   4%|▎         | 7/187 [00:03<01:20,  2.24it/s]

Batches:   4%|▍         | 8/187 [00:03<01:19,  2.26it/s]

Batches:   5%|▍         | 9/187 [00:04<01:20,  2.22it/s]

Batches:   5%|▌         | 10/187 [00:04<01:20,  2.20it/s]

Batches:   6%|▌         | 11/187 [00:04<01:20,  2.18it/s]

Batches:   6%|▋         | 12/187 [00:05<01:20,  2.18it/s]

Batches:   7%|▋         | 13/187 [00:05<01:19,  2.19it/s]

Batches:   7%|▋         | 14/187 [00:06<01:18,  2.19it/s]

Batches:   8%|▊         | 15/187 [00:06<01:18,  2.19it/s]

Batches:   9%|▊         | 16/187 [00:07<01:17,  2.20it/s]

Batches:   9%|▉         | 17/187 [00:07<01:15,  2.25it/s]

Batches:  10%|▉         | 18/187 [00:08<01:14,  2.28it/s]

Batches:  10%|█         | 19/187 [00:08<01:13,  2.28it/s]

Batches:  11%|█         | 20/187 [00:08<01:12,  2.30it/s]

Batches:  11%|█         | 21/187 [00:09<01:11,  2.31it/s]

Batches:  12%|█▏        | 22/187 [00:09<01:11,  2.31it/s]

Batches:  12%|█▏        | 23/187 [00:10<01:11,  2.30it/s]

Batches:  13%|█▎        | 24/187 [00:10<01:10,  2.31it/s]

Batches:  13%|█▎        | 25/187 [00:11<01:10,  2.31it/s]

Batches:  14%|█▍        | 26/187 [00:11<01:10,  2.29it/s]

Batches:  14%|█▍        | 27/187 [00:12<01:11,  2.24it/s]

Batches:  15%|█▍        | 28/187 [00:12<01:12,  2.21it/s]

Batches:  16%|█▌        | 29/187 [00:12<01:11,  2.20it/s]

Batches:  16%|█▌        | 30/187 [00:13<01:12,  2.17it/s]

Batches:  17%|█▋        | 31/187 [00:13<01:11,  2.18it/s]

Batches:  17%|█▋        | 32/187 [00:14<01:10,  2.19it/s]

Batches:  18%|█▊        | 33/187 [00:14<01:10,  2.18it/s]

Batches:  18%|█▊        | 34/187 [00:15<01:08,  2.22it/s]

Batches:  19%|█▊        | 35/187 [00:15<01:07,  2.25it/s]

Batches:  19%|█▉        | 36/187 [00:16<01:06,  2.26it/s]

Batches:  20%|█▉        | 37/187 [00:16<01:06,  2.26it/s]

Batches:  20%|██        | 38/187 [00:17<01:06,  2.23it/s]

Batches:  21%|██        | 39/187 [00:17<01:05,  2.25it/s]

Batches:  21%|██▏       | 40/187 [00:17<01:04,  2.27it/s]

Batches:  22%|██▏       | 41/187 [00:18<01:04,  2.26it/s]

Batches:  22%|██▏       | 42/187 [00:18<01:04,  2.23it/s]

Batches:  23%|██▎       | 43/187 [00:19<01:05,  2.20it/s]

Batches:  24%|██▎       | 44/187 [00:19<01:04,  2.23it/s]

Batches:  24%|██▍       | 45/187 [00:20<01:03,  2.25it/s]

Batches:  25%|██▍       | 46/187 [00:20<01:02,  2.26it/s]

Batches:  25%|██▌       | 47/187 [00:21<01:01,  2.27it/s]

Batches:  26%|██▌       | 48/187 [00:21<01:00,  2.29it/s]

Batches:  26%|██▌       | 49/187 [00:21<01:00,  2.30it/s]

Batches:  27%|██▋       | 50/187 [00:22<00:59,  2.30it/s]

Batches:  27%|██▋       | 51/187 [00:22<00:59,  2.30it/s]

Batches:  28%|██▊       | 52/187 [00:23<00:59,  2.26it/s]

Batches:  28%|██▊       | 53/187 [00:23<01:00,  2.23it/s]

Batches:  29%|██▉       | 54/187 [00:24<01:00,  2.21it/s]

Batches:  29%|██▉       | 55/187 [00:24<01:00,  2.20it/s]

Batches:  30%|██▉       | 56/187 [00:25<01:00,  2.18it/s]

Batches:  30%|███       | 57/187 [00:25<00:58,  2.23it/s]

Batches:  31%|███       | 58/187 [00:25<00:57,  2.25it/s]

Batches:  32%|███▏      | 59/187 [00:26<00:57,  2.24it/s]

Batches:  32%|███▏      | 60/187 [00:26<00:56,  2.24it/s]

Batches:  33%|███▎      | 61/187 [00:27<00:56,  2.22it/s]

Batches:  33%|███▎      | 62/187 [00:27<00:56,  2.22it/s]

Batches:  34%|███▎      | 63/187 [00:28<00:55,  2.24it/s]

Batches:  34%|███▍      | 64/187 [00:28<00:55,  2.20it/s]

Batches:  35%|███▍      | 65/187 [00:29<00:55,  2.19it/s]

Batches:  35%|███▌      | 66/187 [00:29<00:55,  2.17it/s]

Batches:  36%|███▌      | 67/187 [00:30<00:54,  2.20it/s]

Batches:  36%|███▋      | 68/187 [00:30<00:53,  2.21it/s]

Batches:  37%|███▋      | 69/187 [00:30<00:53,  2.19it/s]

Batches:  37%|███▋      | 70/187 [00:31<00:52,  2.21it/s]

Batches:  38%|███▊      | 71/187 [00:31<00:52,  2.21it/s]

Batches:  39%|███▊      | 72/187 [00:32<00:52,  2.21it/s]

Batches:  39%|███▉      | 73/187 [00:32<00:51,  2.20it/s]

Batches:  40%|███▉      | 74/187 [00:33<00:51,  2.19it/s]

Batches:  40%|████      | 75/187 [00:33<00:51,  2.18it/s]

Batches:  41%|████      | 76/187 [00:34<00:50,  2.18it/s]

Batches:  41%|████      | 77/187 [00:34<00:50,  2.19it/s]

Batches:  42%|████▏     | 78/187 [00:35<00:49,  2.20it/s]

Batches:  42%|████▏     | 79/187 [00:35<00:48,  2.22it/s]

Batches:  43%|████▎     | 80/187 [00:35<00:48,  2.21it/s]

Batches:  43%|████▎     | 81/187 [00:36<00:48,  2.17it/s]

Batches:  44%|████▍     | 82/187 [00:36<00:47,  2.20it/s]

Batches:  44%|████▍     | 83/187 [00:37<00:47,  2.18it/s]

Batches:  45%|████▍     | 84/187 [00:37<00:47,  2.18it/s]

Batches:  45%|████▌     | 85/187 [00:38<00:46,  2.20it/s]

Batches:  46%|████▌     | 86/187 [00:38<00:45,  2.23it/s]

Batches:  47%|████▋     | 87/187 [00:39<00:45,  2.21it/s]

Batches:  47%|████▋     | 88/187 [00:39<00:44,  2.21it/s]

Batches:  48%|████▊     | 89/187 [00:40<00:44,  2.18it/s]

Batches:  48%|████▊     | 90/187 [00:40<00:44,  2.17it/s]

Batches:  49%|████▊     | 91/187 [00:40<00:43,  2.22it/s]

Batches:  49%|████▉     | 92/187 [00:41<00:42,  2.25it/s]

Batches:  50%|████▉     | 93/187 [00:41<00:42,  2.23it/s]

Batches:  50%|█████     | 94/187 [00:42<00:41,  2.22it/s]

Batches:  51%|█████     | 95/187 [00:42<00:41,  2.21it/s]

Batches:  51%|█████▏    | 96/187 [00:43<00:40,  2.22it/s]

Batches:  52%|█████▏    | 97/187 [00:43<00:40,  2.24it/s]

Batches:  52%|█████▏    | 98/187 [00:44<00:39,  2.25it/s]

Batches:  53%|█████▎    | 99/187 [00:44<00:39,  2.25it/s]

Batches:  53%|█████▎    | 100/187 [00:44<00:38,  2.27it/s]

Batches:  54%|█████▍    | 101/187 [00:45<00:37,  2.27it/s]

Batches:  55%|█████▍    | 102/187 [00:45<00:37,  2.29it/s]

Batches:  55%|█████▌    | 103/187 [00:46<00:37,  2.27it/s]

Batches:  56%|█████▌    | 104/187 [00:46<00:36,  2.26it/s]

Batches:  56%|█████▌    | 105/187 [00:47<00:36,  2.22it/s]

Batches:  57%|█████▋    | 106/187 [00:47<00:37,  2.18it/s]

Batches:  57%|█████▋    | 107/187 [00:48<00:36,  2.21it/s]

Batches:  58%|█████▊    | 108/187 [00:48<00:35,  2.23it/s]

Batches:  58%|█████▊    | 109/187 [00:48<00:33,  2.33it/s]

Batches:  59%|█████▉    | 110/187 [00:49<00:32,  2.36it/s]

Batches:  59%|█████▉    | 111/187 [00:49<00:31,  2.39it/s]

Batches:  60%|█████▉    | 112/187 [00:50<00:31,  2.35it/s]

Batches:  60%|██████    | 113/187 [00:50<00:31,  2.34it/s]

Batches:  61%|██████    | 114/187 [00:50<00:31,  2.35it/s]

Batches:  61%|██████▏   | 115/187 [00:51<00:29,  2.46it/s]

Batches:  62%|██████▏   | 116/187 [00:51<00:26,  2.68it/s]

Batches:  63%|██████▎   | 117/187 [00:52<00:26,  2.63it/s]

Batches:  63%|██████▎   | 118/187 [00:52<00:27,  2.51it/s]

Batches:  64%|██████▎   | 119/187 [00:52<00:25,  2.65it/s]

Batches:  64%|██████▍   | 120/187 [00:53<00:24,  2.73it/s]

Batches:  65%|██████▍   | 121/187 [00:53<00:24,  2.69it/s]

Batches:  65%|██████▌   | 122/187 [00:53<00:23,  2.81it/s]

Batches:  66%|██████▌   | 123/187 [00:54<00:23,  2.75it/s]

Batches:  66%|██████▋   | 124/187 [00:54<00:22,  2.79it/s]

Batches:  67%|██████▋   | 125/187 [00:54<00:22,  2.82it/s]

Batches:  67%|██████▋   | 126/187 [00:55<00:21,  2.88it/s]

Batches:  68%|██████▊   | 127/187 [00:55<00:20,  2.93it/s]

Batches:  68%|██████▊   | 128/187 [00:55<00:20,  2.92it/s]

Batches:  69%|██████▉   | 129/187 [00:56<00:19,  2.94it/s]

Batches:  70%|██████▉   | 130/187 [00:56<00:18,  3.04it/s]

Batches:  70%|███████   | 131/187 [00:56<00:18,  3.03it/s]

Batches:  71%|███████   | 132/187 [00:57<00:19,  2.89it/s]

Batches:  71%|███████   | 133/187 [00:57<00:17,  3.04it/s]

Batches:  72%|███████▏  | 134/187 [00:57<00:17,  3.03it/s]

Batches:  72%|███████▏  | 135/187 [00:58<00:17,  2.99it/s]

Batches:  73%|███████▎  | 136/187 [00:58<00:16,  3.01it/s]

Batches:  73%|███████▎  | 137/187 [00:58<00:15,  3.25it/s]

Batches:  74%|███████▍  | 138/187 [00:59<00:13,  3.54it/s]

Batches:  74%|███████▍  | 139/187 [00:59<00:13,  3.63it/s]

Batches:  75%|███████▍  | 140/187 [00:59<00:12,  3.63it/s]

Batches:  75%|███████▌  | 141/187 [00:59<00:12,  3.76it/s]

Batches:  76%|███████▌  | 142/187 [01:00<00:12,  3.71it/s]

Batches:  76%|███████▋  | 143/187 [01:00<00:11,  3.76it/s]

Batches:  77%|███████▋  | 144/187 [01:00<00:11,  3.84it/s]

Batches:  78%|███████▊  | 145/187 [01:00<00:10,  3.86it/s]

Batches:  78%|███████▊  | 146/187 [01:01<00:10,  4.04it/s]

Batches:  79%|███████▊  | 147/187 [01:01<00:09,  4.15it/s]

Batches:  79%|███████▉  | 148/187 [01:01<00:09,  4.14it/s]

Batches:  80%|███████▉  | 149/187 [01:01<00:08,  4.43it/s]

Batches:  80%|████████  | 150/187 [01:01<00:08,  4.35it/s]

Batches:  81%|████████  | 151/187 [01:02<00:08,  4.43it/s]

Batches:  81%|████████▏ | 152/187 [01:02<00:07,  4.51it/s]

Batches:  82%|████████▏ | 153/187 [01:02<00:07,  4.86it/s]

Batches:  82%|████████▏ | 154/187 [01:02<00:06,  5.05it/s]

Batches:  83%|████████▎ | 155/187 [01:02<00:06,  5.23it/s]

Batches:  83%|████████▎ | 156/187 [01:03<00:06,  5.11it/s]

Batches:  84%|████████▍ | 157/187 [01:03<00:05,  5.17it/s]

Batches:  84%|████████▍ | 158/187 [01:03<00:05,  5.26it/s]

Batches:  85%|████████▌ | 159/187 [01:03<00:05,  5.33it/s]

Batches:  86%|████████▌ | 160/187 [01:03<00:04,  5.55it/s]

Batches:  86%|████████▌ | 161/187 [01:04<00:04,  5.84it/s]

Batches:  87%|████████▋ | 162/187 [01:04<00:04,  6.04it/s]

Batches:  87%|████████▋ | 163/187 [01:04<00:03,  6.20it/s]

Batches:  88%|████████▊ | 164/187 [01:04<00:03,  6.61it/s]

Batches:  88%|████████▊ | 165/187 [01:04<00:03,  7.27it/s]

Batches:  89%|████████▉ | 166/187 [01:04<00:02,  7.63it/s]

Batches:  89%|████████▉ | 167/187 [01:04<00:02,  8.19it/s]

Batches:  90%|████████▉ | 168/187 [01:04<00:02,  8.49it/s]

Batches:  91%|█████████ | 170/187 [01:05<00:01,  9.00it/s]

Batches:  91%|█████████▏| 171/187 [01:05<00:01,  9.15it/s]

Batches:  92%|█████████▏| 172/187 [01:05<00:01,  9.14it/s]

Batches:  93%|█████████▎| 174/187 [01:05<00:01, 10.11it/s]

Batches:  94%|█████████▎| 175/187 [01:05<00:01,  9.87it/s]

Batches:  95%|█████████▍| 177/187 [01:05<00:00, 11.11it/s]

Batches:  96%|█████████▌| 179/187 [01:05<00:00, 12.40it/s]

Batches:  97%|█████████▋| 181/187 [01:06<00:00, 12.60it/s]

Batches:  98%|█████████▊| 184/187 [01:06<00:00, 15.32it/s]

Batches: 100%|██████████| 187/187 [01:06<00:00,  2.82it/s]

Dev: e5_base

Batches:   0%|          | 0/187 [00:00<?, ?it/s]

Batches:   1%|          | 1/187 [00:00<01:42,  1.81it/s]

Batches:   1%|          | 2/187 [00:01<01:44,  1.76it/s]

Batches:   2%|▏         | 3/187 [00:01<01:42,  1.79it/s]

Batches:   2%|▏         | 4/187 [00:02<01:42,  1.78it/s]

Batches:   3%|▎         | 5/187 [00:02<01:40,  1.80it/s]

Batches:   3%|▎         | 6/187 [00:03<01:38,  1.83it/s]

Batches:   4%|▎         | 7/187 [00:03<01:35,  1.88it/s]

Batches:   4%|▍         | 8/187 [00:04<01:33,  1.91it/s]

Batches:   5%|▍         | 9/187 [00:04<01:32,  1.93it/s]

Batches:   5%|▌         | 10/187 [00:05<01:30,  1.95it/s]

Batches:   6%|▌         | 11/187 [00:05<01:30,  1.94it/s]

Batches:   6%|▋         | 12/187 [00:06<01:29,  1.95it/s]

Batches:   7%|▋         | 13/187 [00:06<01:29,  1.95it/s]

Batches:   7%|▋         | 14/187 [00:07<01:28,  1.95it/s]

Batches:   8%|▊         | 15/187 [00:07<01:29,  1.92it/s]

Batches:   9%|▊         | 16/187 [00:08<01:28,  1.92it/s]

Batches:   9%|▉         | 17/187 [00:08<01:28,  1.93it/s]

Batches:  10%|▉         | 18/187 [00:09<01:26,  1.96it/s]

Batches:  10%|█         | 19/187 [00:09<01:26,  1.95it/s]

Batches:  11%|█         | 20/187 [00:10<01:26,  1.93it/s]

Batches:  11%|█         | 21/187 [00:11<01:26,  1.92it/s]

Batches:  12%|█▏        | 22/187 [00:11<01:24,  1.95it/s]

Batches:  12%|█▏        | 23/187 [00:12<01:24,  1.94it/s]

Batches:  13%|█▎        | 24/187 [00:12<01:24,  1.93it/s]

Batches:  13%|█▎        | 25/187 [00:13<01:24,  1.91it/s]

Batches:  14%|█▍        | 26/187 [00:13<01:23,  1.92it/s]

Batches:  14%|█▍        | 27/187 [00:14<01:23,  1.93it/s]

Batches:  15%|█▍        | 28/187 [00:14<01:22,  1.93it/s]

Batches:  16%|█▌        | 29/187 [00:15<01:22,  1.91it/s]

Batches:  16%|█▌        | 30/187 [00:15<01:23,  1.89it/s]

Batches:  17%|█▋        | 31/187 [00:16<01:22,  1.88it/s]

Batches:  17%|█▋        | 32/187 [00:16<01:22,  1.88it/s]

Batches:  18%|█▊        | 33/187 [00:17<01:22,  1.87it/s]

Batches:  18%|█▊        | 34/187 [00:17<01:21,  1.88it/s]

Batches:  19%|█▊        | 35/187 [00:18<01:21,  1.87it/s]

Batches:  19%|█▉        | 36/187 [00:18<01:19,  1.90it/s]

Batches:  20%|█▉        | 37/187 [00:19<01:19,  1.90it/s]

Batches:  20%|██        | 38/187 [00:20<01:20,  1.85it/s]

Batches:  21%|██        | 39/187 [00:20<01:20,  1.84it/s]

Batches:  21%|██▏       | 40/187 [00:21<01:20,  1.82it/s]

Batches:  22%|██▏       | 41/187 [00:21<01:20,  1.80it/s]

Batches:  22%|██▏       | 42/187 [00:22<01:20,  1.79it/s]

Batches:  23%|██▎       | 43/187 [00:22<01:20,  1.80it/s]

Batches:  24%|██▎       | 44/187 [00:23<01:20,  1.78it/s]

Batches:  24%|██▍       | 45/187 [00:23<01:17,  1.83it/s]

Batches:  25%|██▍       | 46/187 [00:24<01:16,  1.84it/s]

Batches:  25%|██▌       | 47/187 [00:24<01:16,  1.83it/s]

Batches:  26%|██▌       | 48/187 [00:25<01:15,  1.84it/s]

Batches:  26%|██▌       | 49/187 [00:26<01:13,  1.88it/s]

Batches:  27%|██▋       | 50/187 [00:26<01:11,  1.91it/s]

Batches:  27%|██▋       | 51/187 [00:27<01:10,  1.93it/s]

Batches:  28%|██▊       | 52/187 [00:27<01:10,  1.91it/s]

Batches:  28%|██▊       | 53/187 [00:28<01:10,  1.91it/s]

Batches:  29%|██▉       | 54/187 [00:28<01:08,  1.94it/s]

Batches:  29%|██▉       | 55/187 [00:29<01:07,  1.95it/s]

Batches:  30%|██▉       | 56/187 [00:29<01:06,  1.96it/s]

Batches:  30%|███       | 57/187 [00:30<01:06,  1.95it/s]

Batches:  31%|███       | 58/187 [00:30<01:05,  1.96it/s]

Batches:  32%|███▏      | 59/187 [00:31<01:04,  1.97it/s]

Batches:  32%|███▏      | 60/187 [00:31<01:04,  1.98it/s]

Batches:  33%|███▎      | 61/187 [00:32<01:03,  1.98it/s]

Batches:  33%|███▎      | 62/187 [00:32<01:03,  1.98it/s]

Batches:  34%|███▎      | 63/187 [00:33<01:02,  1.98it/s]

Batches:  34%|███▍      | 64/187 [00:33<01:02,  1.97it/s]

Batches:  35%|███▍      | 65/187 [00:34<01:02,  1.96it/s]

Batches:  35%|███▌      | 66/187 [00:34<01:01,  1.97it/s]

Batches:  36%|███▌      | 67/187 [00:35<01:00,  1.97it/s]

Batches:  36%|███▋      | 68/187 [00:35<01:00,  1.97it/s]

Batches:  37%|███▋      | 69/187 [00:36<00:59,  1.98it/s]

Batches:  37%|███▋      | 70/187 [00:36<00:59,  1.98it/s]

Batches:  38%|███▊      | 71/187 [00:37<00:58,  1.98it/s]

Batches:  39%|███▊      | 72/187 [00:37<00:58,  1.96it/s]

Batches:  39%|███▉      | 73/187 [00:38<00:58,  1.95it/s]

Batches:  40%|███▉      | 74/187 [00:38<00:57,  1.97it/s]

Batches:  40%|████      | 75/187 [00:39<00:56,  1.98it/s]

Batches:  41%|████      | 76/187 [00:39<00:56,  1.98it/s]

Batches:  41%|████      | 77/187 [00:40<00:55,  1.98it/s]

Batches:  42%|████▏     | 78/187 [00:40<00:54,  1.99it/s]

Batches:  42%|████▏     | 79/187 [00:41<00:54,  1.98it/s]

Batches:  43%|████▎     | 80/187 [00:41<00:54,  1.98it/s]

Batches:  43%|████▎     | 81/187 [00:42<00:53,  1.98it/s]

Batches:  44%|████▍     | 82/187 [00:42<00:52,  1.98it/s]

Batches:  44%|████▍     | 83/187 [00:43<00:52,  1.99it/s]

Batches:  45%|████▍     | 84/187 [00:43<00:51,  1.99it/s]

Batches:  45%|████▌     | 85/187 [00:44<00:51,  1.99it/s]

Batches:  46%|████▌     | 86/187 [00:44<00:50,  1.99it/s]

Batches:  47%|████▋     | 87/187 [00:45<00:50,  1.97it/s]

Batches:  47%|████▋     | 88/187 [00:45<00:50,  1.96it/s]

Batches:  48%|████▊     | 89/187 [00:46<00:50,  1.95it/s]

Batches:  48%|████▊     | 90/187 [00:46<00:49,  1.96it/s]

Batches:  49%|████▊     | 91/187 [00:47<00:48,  1.99it/s]

Batches:  49%|████▉     | 92/187 [00:47<00:47,  1.99it/s]

Batches:  50%|████▉     | 93/187 [00:48<00:45,  2.07it/s]

Batches:  50%|█████     | 94/187 [00:48<00:45,  2.04it/s]

Batches:  51%|█████     | 95/187 [00:49<00:45,  2.02it/s]

Batches:  51%|█████▏    | 96/187 [00:49<00:44,  2.03it/s]

Batches:  52%|█████▏    | 97/187 [00:50<00:45,  2.00it/s]

Batches:  52%|█████▏    | 98/187 [00:50<00:44,  2.00it/s]

Batches:  53%|█████▎    | 99/187 [00:51<00:43,  2.00it/s]

Batches:  53%|█████▎    | 100/187 [00:51<00:42,  2.06it/s]

Batches:  54%|█████▍    | 101/187 [00:52<00:42,  2.04it/s]

Batches:  55%|█████▍    | 102/187 [00:52<00:41,  2.04it/s]

Batches:  55%|█████▌    | 103/187 [00:53<00:40,  2.10it/s]

Batches:  56%|█████▌    | 104/187 [00:53<00:38,  2.17it/s]

Batches:  56%|█████▌    | 105/187 [00:54<00:38,  2.11it/s]

Batches:  57%|█████▋    | 106/187 [00:54<00:39,  2.06it/s]

Batches:  57%|█████▋    | 107/187 [00:55<00:38,  2.10it/s]

Batches:  58%|█████▊    | 108/187 [00:55<00:36,  2.16it/s]

Batches:  58%|█████▊    | 109/187 [00:55<00:33,  2.36it/s]

Batches:  59%|█████▉    | 110/187 [00:56<00:31,  2.48it/s]

Batches:  59%|█████▉    | 111/187 [00:56<00:30,  2.52it/s]

Batches:  60%|█████▉    | 112/187 [00:57<00:32,  2.33it/s]

Batches:  60%|██████    | 113/187 [00:57<00:31,  2.38it/s]

Batches:  61%|██████    | 114/187 [00:57<00:30,  2.40it/s]

Batches:  61%|██████▏   | 115/187 [00:58<00:28,  2.56it/s]

Batches:  62%|██████▏   | 116/187 [00:58<00:25,  2.84it/s]

Batches:  63%|██████▎   | 117/187 [00:58<00:24,  2.87it/s]

Batches:  63%|██████▎   | 118/187 [00:59<00:25,  2.73it/s]

Batches:  64%|██████▎   | 119/187 [00:59<00:23,  2.87it/s]

Batches:  64%|██████▍   | 120/187 [00:59<00:22,  3.00it/s]

Batches:  65%|██████▍   | 121/187 [01:00<00:22,  2.97it/s]

Batches:  65%|██████▌   | 122/187 [01:00<00:20,  3.10it/s]

Batches:  66%|██████▌   | 123/187 [01:00<00:20,  3.08it/s]

Batches:  66%|██████▋   | 124/187 [01:01<00:19,  3.16it/s]

Batches:  67%|██████▋   | 125/187 [01:01<00:19,  3.20it/s]

Batches:  67%|██████▋   | 126/187 [01:01<00:18,  3.26it/s]

Batches:  68%|██████▊   | 127/187 [01:01<00:18,  3.27it/s]

Batches:  68%|██████▊   | 128/187 [01:02<00:17,  3.31it/s]

Batches:  69%|██████▉   | 129/187 [01:02<00:17,  3.35it/s]

Batches:  70%|██████▉   | 130/187 [01:02<00:16,  3.50it/s]

Batches:  70%|███████   | 131/187 [01:03<00:15,  3.50it/s]

Batches:  71%|███████   | 132/187 [01:03<00:15,  3.44it/s]

Batches:  71%|███████   | 133/187 [01:03<00:14,  3.67it/s]

Batches:  72%|███████▏  | 134/187 [01:03<00:14,  3.74it/s]

Batches:  72%|███████▏  | 135/187 [01:04<00:14,  3.71it/s]

Batches:  73%|███████▎  | 136/187 [01:04<00:13,  3.72it/s]

Batches:  73%|███████▎  | 137/187 [01:04<00:12,  3.95it/s]

Batches:  74%|███████▍  | 138/187 [01:04<00:11,  4.16it/s]

Batches:  74%|███████▍  | 139/187 [01:05<00:11,  4.18it/s]

Batches:  75%|███████▍  | 140/187 [01:05<00:11,  4.14it/s]

Batches:  75%|███████▌  | 141/187 [01:05<00:10,  4.31it/s]

Batches:  76%|███████▌  | 142/187 [01:05<00:10,  4.30it/s]

Batches:  76%|███████▋  | 143/187 [01:06<00:10,  4.37it/s]

Batches:  77%|███████▋  | 144/187 [01:06<00:09,  4.42it/s]

Batches:  78%|███████▊  | 145/187 [01:06<00:09,  4.43it/s]

Batches:  78%|███████▊  | 146/187 [01:06<00:09,  4.53it/s]

Batches:  79%|███████▊  | 147/187 [01:06<00:08,  4.59it/s]

Batches:  79%|███████▉  | 148/187 [01:07<00:08,  4.61it/s]

Batches:  80%|███████▉  | 149/187 [01:07<00:07,  4.87it/s]

Batches:  80%|████████  | 150/187 [01:07<00:07,  4.82it/s]

Batches:  81%|████████  | 151/187 [01:07<00:07,  4.83it/s]

Batches:  81%|████████▏ | 152/187 [01:07<00:07,  4.89it/s]

Batches:  82%|████████▏ | 153/187 [01:08<00:06,  5.21it/s]

Batches:  82%|████████▏ | 154/187 [01:08<00:06,  5.39it/s]

Batches:  83%|████████▎ | 155/187 [01:08<00:05,  5.59it/s]

Batches:  83%|████████▎ | 156/187 [01:08<00:05,  5.59it/s]

Batches:  84%|████████▍ | 157/187 [01:08<00:05,  5.76it/s]

Batches:  84%|████████▍ | 158/187 [01:08<00:04,  5.96it/s]

Batches:  85%|████████▌ | 159/187 [01:09<00:04,  6.13it/s]

Batches:  86%|████████▌ | 160/187 [01:09<00:04,  6.34it/s]

Batches:  86%|████████▌ | 161/187 [01:09<00:03,  6.71it/s]

Batches:  87%|████████▋ | 162/187 [01:09<00:03,  6.84it/s]

Batches:  87%|████████▋ | 163/187 [01:09<00:03,  7.07it/s]

Batches:  88%|████████▊ | 164/187 [01:09<00:03,  7.23it/s]

Batches:  89%|████████▉ | 166/187 [01:09<00:02,  8.15it/s]

Batches:  89%|████████▉ | 167/187 [01:10<00:02,  8.53it/s]

Batches:  90%|████████▉ | 168/187 [01:10<00:02,  8.70it/s]

Batches:  91%|█████████ | 170/187 [01:10<00:01,  9.10it/s]

Batches:  91%|█████████▏| 171/187 [01:10<00:01,  9.25it/s]

Batches:  92%|█████████▏| 172/187 [01:10<00:01,  9.24it/s]

Batches:  93%|█████████▎| 174/187 [01:10<00:01, 10.14it/s]

Batches:  94%|█████████▍| 176/187 [01:10<00:01, 10.59it/s]

Batches:  95%|█████████▌| 178/187 [01:11<00:00, 11.99it/s]

Batches:  96%|█████████▋| 180/187 [01:11<00:00, 12.71it/s]

Batches:  97%|█████████▋| 182/187 [01:11<00:00, 14.13it/s]

Batches:  99%|█████████▉| 185/187 [01:11<00:00, 16.97it/s]

Batches: 100%|██████████| 187/187 [01:11<00:00,  2.62it/s]

Dev: bge_base

Batches:   0%|          | 0/187 [00:00<?, ?it/s]

Batches:   1%|          | 1/187 [00:00<01:39,  1.87it/s]

Batches:   1%|          | 2/187 [00:01<01:35,  1.95it/s]

Batches:   2%|▏         | 3/187 [00:01<01:32,  1.99it/s]

Batches:   2%|▏         | 4/187 [00:02<01:32,  1.99it/s]

Batches:   3%|▎         | 5/187 [00:02<01:31,  1.98it/s]

Batches:   3%|▎         | 6/187 [00:03<01:31,  1.97it/s]

Batches:   4%|▎         | 7/187 [00:03<01:31,  1.98it/s]

Batches:   4%|▍         | 8/187 [00:04<01:30,  1.99it/s]

Batches:   5%|▍         | 9/187 [00:04<01:29,  1.99it/s]

Batches:   5%|▌         | 10/187 [00:05<01:29,  1.99it/s]

Batches:   6%|▌         | 11/187 [00:05<01:28,  1.98it/s]

Batches:   6%|▋         | 12/187 [00:06<01:28,  1.98it/s]

Batches:   7%|▋         | 13/187 [00:06<01:28,  1.97it/s]

Batches:   7%|▋         | 14/187 [00:07<01:27,  1.98it/s]

Batches:   8%|▊         | 15/187 [00:07<01:26,  1.98it/s]

Batches:   9%|▊         | 16/187 [00:08<01:26,  1.98it/s]

Batches:   9%|▉         | 17/187 [00:08<01:25,  1.99it/s]

Batches:  10%|▉         | 18/187 [00:09<01:24,  2.00it/s]

Batches:  10%|█         | 19/187 [00:09<01:23,  2.00it/s]

Batches:  11%|█         | 20/187 [00:10<01:23,  1.99it/s]

Batches:  11%|█         | 21/187 [00:10<01:24,  1.98it/s]

Batches:  12%|█▏        | 22/187 [00:11<01:23,  1.98it/s]

Batches:  12%|█▏        | 23/187 [00:11<01:22,  1.98it/s]

Batches:  13%|█▎        | 24/187 [00:12<01:21,  1.99it/s]

Batches:  13%|█▎        | 25/187 [00:12<01:21,  2.00it/s]

Batches:  14%|█▍        | 26/187 [00:13<01:20,  2.00it/s]

Batches:  14%|█▍        | 27/187 [00:13<01:19,  2.01it/s]

Batches:  15%|█▍        | 28/187 [00:14<01:19,  2.00it/s]

Batches:  16%|█▌        | 29/187 [00:14<01:19,  1.98it/s]

Batches:  16%|█▌        | 30/187 [00:15<01:19,  1.98it/s]

Batches:  17%|█▋        | 31/187 [00:15<01:18,  1.98it/s]

Batches:  17%|█▋        | 32/187 [00:16<01:18,  1.97it/s]

Batches:  18%|█▊        | 33/187 [00:16<01:19,  1.94it/s]

Batches:  18%|█▊        | 34/187 [00:17<01:18,  1.95it/s]

Batches:  19%|█▊        | 35/187 [00:17<01:17,  1.96it/s]

Batches:  19%|█▉        | 36/187 [00:18<01:17,  1.96it/s]

Batches:  20%|█▉        | 37/187 [00:18<01:18,  1.92it/s]

Batches:  20%|██        | 38/187 [00:19<01:17,  1.92it/s]

Batches:  21%|██        | 39/187 [00:19<01:16,  1.94it/s]

Batches:  21%|██▏       | 40/187 [00:20<01:15,  1.96it/s]

Batches:  22%|██▏       | 41/187 [00:20<01:14,  1.96it/s]

Batches:  22%|██▏       | 42/187 [00:21<01:13,  1.97it/s]

Batches:  23%|██▎       | 43/187 [00:21<01:12,  1.97it/s]

Batches:  24%|██▎       | 44/187 [00:22<01:13,  1.94it/s]

Batches:  24%|██▍       | 45/187 [00:22<01:14,  1.92it/s]

Batches:  25%|██▍       | 46/187 [00:23<01:14,  1.90it/s]

Batches:  25%|██▌       | 47/187 [00:23<01:14,  1.88it/s]

Batches:  26%|██▌       | 48/187 [00:24<01:13,  1.89it/s]

Batches:  26%|██▌       | 49/187 [00:24<01:12,  1.89it/s]

Batches:  27%|██▋       | 50/187 [00:25<01:11,  1.92it/s]

Batches:  27%|██▋       | 51/187 [00:25<01:10,  1.94it/s]

Batches:  28%|██▊       | 52/187 [00:26<01:09,  1.94it/s]

Batches:  28%|██▊       | 53/187 [00:27<01:08,  1.95it/s]

Batches:  29%|██▉       | 54/187 [00:27<01:08,  1.96it/s]

Batches:  29%|██▉       | 55/187 [00:28<01:07,  1.97it/s]

Batches:  30%|██▉       | 56/187 [00:28<01:06,  1.98it/s]

Batches:  30%|███       | 57/187 [00:29<01:05,  1.99it/s]

Batches:  31%|███       | 58/187 [00:29<01:04,  1.99it/s]

Batches:  32%|███▏      | 59/187 [00:30<01:04,  1.99it/s]

Batches:  32%|███▏      | 60/187 [00:30<01:04,  1.97it/s]

Batches:  33%|███▎      | 61/187 [00:31<01:04,  1.97it/s]

Batches:  33%|███▎      | 62/187 [00:31<01:03,  1.98it/s]

Batches:  34%|███▎      | 63/187 [00:32<01:03,  1.96it/s]

Batches:  34%|███▍      | 64/187 [00:32<01:03,  1.95it/s]

Batches:  35%|███▍      | 65/187 [00:33<01:02,  1.95it/s]

Batches:  35%|███▌      | 66/187 [00:33<01:02,  1.92it/s]

Batches:  36%|███▌      | 67/187 [00:34<01:03,  1.90it/s]

Batches:  36%|███▋      | 68/187 [00:34<01:02,  1.92it/s]

Batches:  37%|███▋      | 69/187 [00:35<01:00,  1.94it/s]

Batches:  37%|███▋      | 70/187 [00:35<00:59,  1.96it/s]

Batches:  38%|███▊      | 71/187 [00:36<00:58,  1.97it/s]

Batches:  39%|███▊      | 72/187 [00:36<00:58,  1.98it/s]

Batches:  39%|███▉      | 73/187 [00:37<00:57,  1.99it/s]

Batches:  40%|███▉      | 74/187 [00:37<00:56,  1.98it/s]

Batches:  40%|████      | 75/187 [00:38<00:56,  1.98it/s]

Batches:  41%|████      | 76/187 [00:38<00:56,  1.96it/s]

Batches:  41%|████      | 77/187 [00:39<00:55,  1.97it/s]

Batches:  42%|████▏     | 78/187 [00:39<00:55,  1.98it/s]

Batches:  42%|████▏     | 79/187 [00:40<00:54,  1.97it/s]

Batches:  43%|████▎     | 80/187 [00:40<00:54,  1.98it/s]

Batches:  43%|████▎     | 81/187 [00:41<00:53,  1.98it/s]

Batches:  44%|████▍     | 82/187 [00:41<00:52,  1.98it/s]

Batches:  44%|████▍     | 83/187 [00:42<00:52,  1.97it/s]

Batches:  45%|████▍     | 84/187 [00:42<00:52,  1.96it/s]

Batches:  45%|████▌     | 85/187 [00:43<00:51,  1.97it/s]

Batches:  46%|████▌     | 86/187 [00:43<00:51,  1.98it/s]

Batches:  47%|████▋     | 87/187 [00:44<00:50,  1.98it/s]

Batches:  47%|████▋     | 88/187 [00:44<00:49,  1.98it/s]

Batches:  48%|████▊     | 89/187 [00:45<00:49,  1.99it/s]

Batches:  48%|████▊     | 90/187 [00:45<00:48,  1.99it/s]

Batches:  49%|████▊     | 91/187 [00:46<00:48,  2.00it/s]

Batches:  49%|████▉     | 92/187 [00:46<00:47,  1.99it/s]

Batches:  50%|████▉     | 93/187 [00:47<00:45,  2.07it/s]

Batches:  50%|█████     | 94/187 [00:47<00:45,  2.05it/s]

Batches:  51%|█████     | 95/187 [00:48<00:45,  2.04it/s]

Batches:  51%|█████▏    | 96/187 [00:48<00:44,  2.06it/s]

Batches:  52%|█████▏    | 97/187 [00:49<00:44,  2.04it/s]

Batches:  52%|█████▏    | 98/187 [00:49<00:43,  2.05it/s]

Batches:  53%|█████▎    | 99/187 [00:50<00:43,  2.02it/s]

Batches:  53%|█████▎    | 100/187 [00:50<00:42,  2.06it/s]

Batches:  54%|█████▍    | 101/187 [00:51<00:42,  2.03it/s]

Batches:  55%|█████▍    | 102/187 [00:51<00:41,  2.05it/s]

Batches:  55%|█████▌    | 103/187 [00:52<00:39,  2.15it/s]

Batches:  56%|█████▌    | 104/187 [00:52<00:36,  2.25it/s]

Batches:  56%|█████▌    | 105/187 [00:52<00:37,  2.19it/s]

Batches:  57%|█████▋    | 106/187 [00:53<00:38,  2.13it/s]

Batches:  57%|█████▋    | 107/187 [00:53<00:36,  2.20it/s]

Batches:  58%|█████▊    | 108/187 [00:54<00:35,  2.23it/s]

Batches:  58%|█████▊    | 109/187 [00:54<00:32,  2.40it/s]

Batches:  59%|█████▉    | 110/187 [00:54<00:30,  2.53it/s]

Batches:  59%|█████▉    | 111/187 [00:55<00:29,  2.62it/s]

Batches:  60%|█████▉    | 112/187 [00:55<00:31,  2.39it/s]

Batches:  60%|██████    | 113/187 [00:56<00:30,  2.44it/s]

Batches:  61%|██████    | 114/187 [00:56<00:29,  2.48it/s]

Batches:  61%|██████▏   | 115/187 [00:56<00:27,  2.65it/s]

Batches:  62%|██████▏   | 116/187 [00:57<00:24,  2.92it/s]

Batches:  63%|██████▎   | 117/187 [00:57<00:23,  2.93it/s]

Batches:  63%|██████▎   | 118/187 [00:57<00:24,  2.77it/s]

Batches:  64%|██████▎   | 119/187 [00:58<00:23,  2.94it/s]

Batches:  64%|██████▍   | 120/187 [00:58<00:21,  3.06it/s]

Batches:  65%|██████▍   | 121/187 [00:58<00:21,  3.06it/s]

Batches:  65%|██████▌   | 122/187 [00:59<00:19,  3.25it/s]

Batches:  66%|██████▌   | 123/187 [00:59<00:19,  3.22it/s]

Batches:  66%|██████▋   | 124/187 [00:59<00:19,  3.28it/s]

Batches:  67%|██████▋   | 125/187 [01:00<00:18,  3.33it/s]

Batches:  67%|██████▋   | 126/187 [01:00<00:18,  3.38it/s]

Batches:  68%|██████▊   | 127/187 [01:00<00:17,  3.46it/s]

Batches:  68%|██████▊   | 128/187 [01:00<00:16,  3.47it/s]

Batches:  69%|██████▉   | 129/187 [01:01<00:16,  3.58it/s]

Batches:  70%|██████▉   | 130/187 [01:01<00:15,  3.70it/s]

Batches:  70%|███████   | 131/187 [01:01<00:14,  3.75it/s]

Batches:  71%|███████   | 132/187 [01:01<00:14,  3.67it/s]

Batches:  71%|███████   | 133/187 [01:02<00:14,  3.82it/s]

Batches:  72%|███████▏  | 134/187 [01:02<00:13,  3.79it/s]

Batches:  72%|███████▏  | 135/187 [01:02<00:13,  3.73it/s]

Batches:  73%|███████▎  | 136/187 [01:02<00:13,  3.78it/s]

Batches:  73%|███████▎  | 137/187 [01:03<00:12,  4.02it/s]

Batches:  74%|███████▍  | 138/187 [01:03<00:11,  4.31it/s]

Batches:  74%|███████▍  | 139/187 [01:03<00:10,  4.36it/s]

Batches:  75%|███████▍  | 140/187 [01:03<00:10,  4.42it/s]

Batches:  75%|███████▌  | 141/187 [01:03<00:09,  4.62it/s]

Batches:  76%|███████▌  | 142/187 [01:04<00:09,  4.65it/s]

Batches:  76%|███████▋  | 143/187 [01:04<00:09,  4.73it/s]

Batches:  77%|███████▋  | 144/187 [01:04<00:09,  4.76it/s]

Batches:  78%|███████▊  | 145/187 [01:04<00:08,  4.81it/s]

Batches:  78%|███████▊  | 146/187 [01:05<00:08,  4.93it/s]

Batches:  79%|███████▊  | 147/187 [01:05<00:08,  4.96it/s]

Batches:  79%|███████▉  | 148/187 [01:05<00:07,  4.91it/s]

Batches:  80%|███████▉  | 149/187 [01:05<00:07,  5.20it/s]

Batches:  80%|████████  | 150/187 [01:05<00:07,  5.14it/s]

Batches:  81%|████████  | 151/187 [01:05<00:06,  5.16it/s]

Batches:  81%|████████▏ | 152/187 [01:06<00:06,  5.16it/s]

Batches:  82%|████████▏ | 153/187 [01:06<00:06,  5.52it/s]

Batches:  82%|████████▏ | 154/187 [01:06<00:05,  5.72it/s]

Batches:  83%|████████▎ | 155/187 [01:06<00:05,  5.92it/s]

Batches:  83%|████████▎ | 156/187 [01:06<00:05,  5.87it/s]

Batches:  84%|████████▍ | 157/187 [01:06<00:04,  6.08it/s]

Batches:  84%|████████▍ | 158/187 [01:07<00:04,  6.25it/s]

Batches:  85%|████████▌ | 159/187 [01:07<00:04,  6.37it/s]

Batches:  86%|████████▌ | 160/187 [01:07<00:04,  6.56it/s]

Batches:  86%|████████▌ | 161/187 [01:07<00:03,  6.83it/s]

Batches:  87%|████████▋ | 162/187 [01:07<00:03,  7.02it/s]

Batches:  87%|████████▋ | 163/187 [01:07<00:03,  7.25it/s]

Batches:  88%|████████▊ | 164/187 [01:07<00:03,  7.45it/s]

Batches:  88%|████████▊ | 165/187 [01:08<00:02,  7.99it/s]

Batches:  89%|████████▉ | 166/187 [01:08<00:02,  8.23it/s]

Batches:  89%|████████▉ | 167/187 [01:08<00:02,  8.67it/s]

Batches:  90%|█████████ | 169/187 [01:08<00:01,  9.58it/s]

Batches:  91%|█████████▏| 171/187 [01:08<00:01,  9.91it/s]

Batches:  93%|█████████▎| 173/187 [01:08<00:01, 10.27it/s]

Batches:  94%|█████████▎| 175/187 [01:08<00:01, 10.93it/s]

Batches:  95%|█████████▍| 177/187 [01:09<00:00, 12.12it/s]

Batches:  96%|█████████▌| 179/187 [01:09<00:00, 13.55it/s]

Batches:  97%|█████████▋| 181/187 [01:09<00:00, 13.90it/s]

Batches:  98%|█████████▊| 184/187 [01:09<00:00, 16.94it/s]

Batches: 100%|██████████| 187/187 [01:09<00:00,  2.69it/s]

Dev: jina

Batches:   0%|          | 0/374 [00:00<?, ?it/s]

Batches:   0%|          | 1/374 [00:00<00:40,  9.20it/s]

Batches:   1%|          | 3/374 [00:00<00:35, 10.38it/s]

Batches:   1%|▏         | 5/374 [00:00<00:35, 10.44it/s]

Batches:   2%|▏         | 7/374 [00:00<00:33, 10.85it/s]

Batches:   2%|▏         | 9/374 [00:00<00:33, 10.89it/s]

Batches:   3%|▎         | 11/374 [00:01<00:35, 10.28it/s]

Batches:   3%|▎         | 13/374 [00:01<00:34, 10.45it/s]

Batches:   4%|▍         | 15/374 [00:01<00:34, 10.49it/s]

Batches:   5%|▍         | 17/374 [00:01<00:33, 10.56it/s]

Batches:   5%|▌         | 19/374 [00:01<00:33, 10.62it/s]

Batches:   6%|▌         | 21/374 [00:01<00:33, 10.59it/s]

Batches:   6%|▌         | 23/374 [00:02<00:32, 10.81it/s]

Batches:   7%|▋         | 25/374 [00:02<00:32, 10.83it/s]

Batches:   7%|▋         | 27/374 [00:02<00:31, 10.93it/s]

Batches:   8%|▊         | 29/374 [00:02<00:31, 11.00it/s]

Batches:   8%|▊         | 31/374 [00:02<00:30, 11.08it/s]

Batches:   9%|▉         | 33/374 [00:03<00:30, 11.20it/s]

Batches:   9%|▉         | 35/374 [00:03<00:29, 11.35it/s]

Batches:  10%|▉         | 37/374 [00:03<00:29, 11.36it/s]

Batches:  10%|█         | 39/374 [00:03<00:29, 11.37it/s]

Batches:  11%|█         | 41/374 [00:03<00:29, 11.39it/s]

Batches:  11%|█▏        | 43/374 [00:03<00:30, 11.03it/s]

Batches:  12%|█▏        | 45/374 [00:04<00:30, 10.95it/s]

Batches:  13%|█▎        | 47/374 [00:04<00:30, 10.85it/s]

Batches:  13%|█▎        | 49/374 [00:04<00:29, 10.97it/s]

Batches:  14%|█▎        | 51/374 [00:04<00:30, 10.74it/s]

Batches:  14%|█▍        | 53/374 [00:04<00:29, 10.78it/s]

Batches:  15%|█▍        | 55/374 [00:05<00:30, 10.63it/s]

Batches:  15%|█▌        | 57/374 [00:05<00:30, 10.47it/s]

Batches:  16%|█▌        | 59/374 [00:05<00:31, 10.04it/s]

Batches:  16%|█▋        | 61/374 [00:05<00:31,  9.96it/s]

Batches:  17%|█▋        | 63/374 [00:05<00:30, 10.04it/s]

Batches:  17%|█▋        | 65/374 [00:06<00:30, 10.12it/s]

Batches:  18%|█▊        | 67/374 [00:06<00:30, 10.15it/s]

Batches:  18%|█▊        | 69/374 [00:06<00:28, 10.53it/s]

Batches:  19%|█▉        | 71/374 [00:06<00:28, 10.72it/s]

Batches:  20%|█▉        | 73/374 [00:06<00:28, 10.62it/s]

Batches:  20%|██        | 75/374 [00:07<00:28, 10.54it/s]

Batches:  21%|██        | 77/374 [00:07<00:28, 10.37it/s]

Batches:  21%|██        | 79/374 [00:07<00:28, 10.34it/s]

Batches:  22%|██▏       | 81/374 [00:07<00:27, 10.57it/s]

Batches:  22%|██▏       | 83/374 [00:07<00:26, 10.99it/s]

Batches:  23%|██▎       | 85/374 [00:07<00:25, 11.32it/s]

Batches:  23%|██▎       | 87/374 [00:08<00:25, 11.38it/s]

Batches:  24%|██▍       | 89/374 [00:08<00:25, 11.37it/s]

Batches:  24%|██▍       | 91/374 [00:08<00:25, 11.23it/s]

Batches:  25%|██▍       | 93/374 [00:08<00:24, 11.26it/s]

Batches:  25%|██▌       | 95/374 [00:08<00:24, 11.52it/s]

Batches:  26%|██▌       | 97/374 [00:08<00:24, 11.37it/s]

Batches:  26%|██▋       | 99/374 [00:09<00:24, 11.41it/s]

Batches:  27%|██▋       | 101/374 [00:09<00:24, 11.30it/s]

Batches:  28%|██▊       | 103/374 [00:09<00:24, 11.22it/s]

Batches:  28%|██▊       | 105/374 [00:09<00:24, 10.85it/s]

Batches:  29%|██▊       | 107/374 [00:09<00:24, 11.00it/s]

Batches:  29%|██▉       | 109/374 [00:10<00:23, 11.10it/s]

Batches:  30%|██▉       | 111/374 [00:10<00:23, 11.31it/s]

Batches:  30%|███       | 113/374 [00:10<00:22, 11.61it/s]

Batches:  31%|███       | 115/374 [00:10<00:21, 11.89it/s]

Batches:  31%|███▏      | 117/374 [00:10<00:21, 12.13it/s]

Batches:  32%|███▏      | 119/374 [00:10<00:21, 11.74it/s]

Batches:  32%|███▏      | 121/374 [00:11<00:21, 11.74it/s]

Batches:  33%|███▎      | 123/374 [00:11<00:21, 11.75it/s]

Batches:  33%|███▎      | 125/374 [00:11<00:24, 10.07it/s]

Batches:  34%|███▍      | 127/374 [00:11<00:23, 10.68it/s]

Batches:  34%|███▍      | 129/374 [00:11<00:22, 11.12it/s]

Batches:  35%|███▌      | 131/374 [00:11<00:20, 11.59it/s]

Batches:  36%|███▌      | 133/374 [00:12<00:20, 11.73it/s]

Batches:  36%|███▌      | 135/374 [00:12<00:20, 11.47it/s]

Batches:  37%|███▋      | 137/374 [00:12<00:20, 11.60it/s]

Batches:  37%|███▋      | 139/374 [00:12<00:19, 11.91it/s]

Batches:  38%|███▊      | 141/374 [00:12<00:19, 12.09it/s]

Batches:  38%|███▊      | 143/374 [00:12<00:19, 11.91it/s]

Batches:  39%|███▉      | 145/374 [00:13<00:19, 11.77it/s]

Batches:  39%|███▉      | 147/374 [00:13<00:18, 12.07it/s]

Batches:  40%|███▉      | 149/374 [00:13<00:19, 11.36it/s]

Batches:  40%|████      | 151/374 [00:13<00:19, 11.33it/s]

Batches:  41%|████      | 153/374 [00:13<00:19, 11.58it/s]

Batches:  41%|████▏     | 155/374 [00:14<00:19, 11.39it/s]

Batches:  42%|████▏     | 157/374 [00:14<00:18, 11.99it/s]

Batches:  43%|████▎     | 159/374 [00:14<00:17, 12.30it/s]

Batches:  43%|████▎     | 161/374 [00:14<00:17, 12.27it/s]

Batches:  44%|████▎     | 163/374 [00:14<00:17, 12.41it/s]

Batches:  44%|████▍     | 165/374 [00:14<00:16, 12.72it/s]

Batches:  45%|████▍     | 167/374 [00:14<00:16, 12.93it/s]

Batches:  45%|████▌     | 169/374 [00:15<00:15, 13.15it/s]

Batches:  46%|████▌     | 171/374 [00:15<00:15, 13.15it/s]

Batches:  46%|████▋     | 173/374 [00:15<00:15, 13.33it/s]

Batches:  47%|████▋     | 175/374 [00:15<00:15, 12.94it/s]

Batches:  47%|████▋     | 177/374 [00:15<00:14, 13.28it/s]

Batches:  48%|████▊     | 179/374 [00:15<00:14, 13.22it/s]

Batches:  48%|████▊     | 181/374 [00:16<00:14, 12.96it/s]

Batches:  49%|████▉     | 183/374 [00:16<00:14, 13.14it/s]

Batches:  49%|████▉     | 185/374 [00:16<00:13, 13.61it/s]

Batches:  50%|█████     | 187/374 [00:16<00:13, 13.92it/s]

Batches:  51%|█████     | 189/374 [00:16<00:13, 13.83it/s]

Batches:  51%|█████     | 191/374 [00:16<00:12, 14.14it/s]

Batches:  52%|█████▏    | 193/374 [00:16<00:12, 14.19it/s]

Batches:  52%|█████▏    | 195/374 [00:17<00:12, 14.00it/s]

Batches:  53%|█████▎    | 197/374 [00:17<00:12, 13.81it/s]

Batches:  53%|█████▎    | 199/374 [00:17<00:12, 14.20it/s]

Batches:  54%|█████▎    | 201/374 [00:17<00:12, 14.16it/s]

Batches:  54%|█████▍    | 203/374 [00:17<00:11, 14.45it/s]

Batches:  55%|█████▍    | 205/374 [00:17<00:11, 14.80it/s]

Batches:  55%|█████▌    | 207/374 [00:17<00:10, 15.49it/s]

Batches:  56%|█████▌    | 209/374 [00:17<00:10, 15.75it/s]

Batches:  56%|█████▋    | 211/374 [00:18<00:10, 15.06it/s]

Batches:  57%|█████▋    | 213/374 [00:18<00:10, 15.98it/s]

Batches:  57%|█████▋    | 215/374 [00:18<00:09, 16.33it/s]

Batches:  58%|█████▊    | 217/374 [00:18<00:09, 16.92it/s]

Batches:  59%|█████▉    | 220/374 [00:18<00:08, 18.14it/s]

Batches:  60%|█████▉    | 223/374 [00:18<00:08, 18.06it/s]

Batches:  60%|██████    | 225/374 [00:18<00:08, 17.82it/s]

Batches:  61%|██████    | 227/374 [00:18<00:08, 18.15it/s]

Batches:  61%|██████▏   | 230/374 [00:19<00:07, 19.91it/s]

Batches:  62%|██████▏   | 233/374 [00:19<00:06, 21.23it/s]

Batches:  63%|██████▎   | 236/374 [00:19<00:06, 20.76it/s]

Batches:  64%|██████▍   | 239/374 [00:19<00:06, 21.78it/s]

Batches:  65%|██████▍   | 242/374 [00:19<00:05, 22.29it/s]

Batches:  66%|██████▌   | 245/374 [00:19<00:05, 23.28it/s]

Batches:  66%|██████▋   | 248/374 [00:19<00:05, 23.40it/s]

Batches:  67%|██████▋   | 251/374 [00:19<00:05, 23.89it/s]

Batches:  68%|██████▊   | 254/374 [00:20<00:04, 24.59it/s]

Batches:  69%|██████▊   | 257/374 [00:20<00:04, 25.05it/s]

Batches:  70%|██████▉   | 260/374 [00:20<00:04, 26.35it/s]

Batches:  70%|███████   | 263/374 [00:20<00:04, 26.17it/s]

Batches:  71%|███████   | 266/374 [00:20<00:04, 26.42it/s]

Batches:  72%|███████▏  | 269/374 [00:20<00:03, 27.28it/s]

Batches:  73%|███████▎  | 272/374 [00:20<00:03, 27.12it/s]

Batches:  74%|███████▍  | 276/374 [00:20<00:03, 29.67it/s]

Batches:  75%|███████▍  | 280/374 [00:20<00:03, 30.26it/s]

Batches:  76%|███████▌  | 284/374 [00:21<00:02, 31.48it/s]

Batches:  77%|███████▋  | 288/374 [00:21<00:02, 32.73it/s]

Batches:  78%|███████▊  | 292/374 [00:21<00:02, 33.87it/s]

Batches:  79%|███████▉  | 296/374 [00:21<00:02, 34.53it/s]

Batches:  80%|████████  | 300/374 [00:21<00:02, 34.83it/s]

Batches:  81%|████████▏ | 304/374 [00:21<00:01, 36.00it/s]

Batches:  83%|████████▎ | 309/374 [00:21<00:01, 38.78it/s]

Batches:  84%|████████▍ | 314/374 [00:21<00:01, 40.74it/s]

Batches:  85%|████████▌ | 319/374 [00:21<00:01, 42.57it/s]

Batches:  87%|████████▋ | 325/374 [00:22<00:01, 46.29it/s]

Batches:  89%|████████▉ | 332/374 [00:22<00:00, 51.76it/s]

Batches:  91%|█████████ | 339/374 [00:22<00:00, 56.65it/s]

Batches:  93%|█████████▎| 347/374 [00:22<00:00, 61.37it/s]

Batches:  95%|█████████▌| 356/374 [00:22<00:00, 67.84it/s]

Batches:  98%|█████████▊| 365/374 [00:22<00:00, 72.65it/s]

Batches: 100%|██████████| 374/374 [00:22<00:00, 77.50it/s]

Batches: 100%|██████████| 374/374 [00:22<00:00, 16.47it/s]

Dev: gte_modernbert

Dev: nomic

<All keys matched successfully>

Batches:   0%|          | 0/747 [00:00<?, ?it/s]

Batches:   0%|          | 1/747 [00:00<02:42,  4.60it/s]

Batches:   0%|          | 2/747 [00:00<02:39,  4.66it/s]

Batches:   0%|          | 3/747 [00:00<02:37,  4.72it/s]

Batches:   1%|          | 4/747 [00:00<02:37,  4.71it/s]

Batches:   1%|          | 5/747 [00:01<02:38,  4.68it/s]

Batches:   1%|          | 6/747 [00:01<02:36,  4.72it/s]

Batches:   1%|          | 7/747 [00:01<02:36,  4.73it/s]

Batches:   1%|          | 8/747 [00:01<02:33,  4.81it/s]

Batches:   1%|          | 9/747 [00:01<02:33,  4.82it/s]

Batches:   1%|▏         | 10/747 [00:02<02:33,  4.79it/s]

Batches:   1%|▏         | 11/747 [00:02<02:34,  4.78it/s]

Batches:   2%|▏         | 12/747 [00:02<02:33,  4.79it/s]

Batches:   2%|▏         | 13/747 [00:02<02:33,  4.78it/s]

Batches:   2%|▏         | 14/747 [00:02<02:33,  4.76it/s]

Batches:   2%|▏         | 15/747 [00:03<02:36,  4.67it/s]

Batches:   2%|▏         | 16/747 [00:03<02:36,  4.67it/s]

Batches:   2%|▏         | 17/747 [00:03<02:36,  4.66it/s]

Batches:   2%|▏         | 18/747 [00:03<02:33,  4.74it/s]

Batches:   3%|▎         | 19/747 [00:04<02:32,  4.77it/s]

Batches:   3%|▎         | 20/747 [00:04<02:40,  4.52it/s]

Batches:   3%|▎         | 21/747 [00:04<02:35,  4.68it/s]

Batches:   3%|▎         | 22/747 [00:04<02:34,  4.70it/s]

Batches:   3%|▎         | 23/747 [00:04<02:32,  4.75it/s]

Batches:   3%|▎         | 24/747 [00:05<02:29,  4.84it/s]

Batches:   3%|▎         | 25/747 [00:05<02:29,  4.82it/s]

Batches:   3%|▎         | 26/747 [00:05<02:28,  4.85it/s]

Batches:   4%|▎         | 27/747 [00:05<02:29,  4.81it/s]

Batches:   4%|▎         | 28/747 [00:05<02:27,  4.88it/s]

Batches:   4%|▍         | 29/747 [00:06<02:26,  4.90it/s]

Batches:   4%|▍         | 30/747 [00:06<02:27,  4.87it/s]

Batches:   4%|▍         | 31/747 [00:06<02:29,  4.79it/s]

Batches:   4%|▍         | 32/747 [00:06<02:28,  4.82it/s]

Batches:   4%|▍         | 33/747 [00:06<02:29,  4.76it/s]

Batches:   5%|▍         | 34/747 [00:07<02:30,  4.73it/s]

Batches:   5%|▍         | 35/747 [00:07<02:31,  4.69it/s]

Batches:   5%|▍         | 36/747 [00:07<02:29,  4.75it/s]

Batches:   5%|▍         | 37/747 [00:07<02:28,  4.79it/s]

Batches:   5%|▌         | 38/747 [00:07<02:28,  4.77it/s]

Batches:   5%|▌         | 39/747 [00:08<02:28,  4.76it/s]

Batches:   5%|▌         | 40/747 [00:08<02:27,  4.80it/s]

Batches:   5%|▌         | 41/747 [00:08<02:29,  4.71it/s]

Batches:   6%|▌         | 42/747 [00:08<02:31,  4.66it/s]

Batches:   6%|▌         | 43/747 [00:09<02:29,  4.72it/s]

Batches:   6%|▌         | 44/747 [00:09<02:27,  4.78it/s]

Batches:   6%|▌         | 45/747 [00:09<02:26,  4.79it/s]

Batches:   6%|▌         | 46/747 [00:09<02:26,  4.79it/s]

Batches:   6%|▋         | 47/747 [00:09<02:28,  4.71it/s]

Batches:   6%|▋         | 48/747 [00:10<02:28,  4.71it/s]

Batches:   7%|▋         | 49/747 [00:10<02:27,  4.72it/s]

Batches:   7%|▋         | 50/747 [00:10<02:31,  4.61it/s]

Batches:   7%|▋         | 51/747 [00:10<02:30,  4.62it/s]

Batches:   7%|▋         | 52/747 [00:10<02:26,  4.74it/s]

Batches:   7%|▋         | 53/747 [00:11<02:28,  4.69it/s]

Batches:   7%|▋         | 54/747 [00:11<02:28,  4.65it/s]

Batches:   7%|▋         | 55/747 [00:11<02:27,  4.71it/s]

Batches:   7%|▋         | 56/747 [00:11<02:29,  4.61it/s]

Batches:   8%|▊         | 57/747 [00:12<02:29,  4.61it/s]

Batches:   8%|▊         | 58/747 [00:12<02:27,  4.67it/s]

Batches:   8%|▊         | 59/747 [00:12<02:29,  4.61it/s]

Batches:   8%|▊         | 60/747 [00:12<02:30,  4.55it/s]

Batches:   8%|▊         | 61/747 [00:12<02:30,  4.55it/s]

Batches:   8%|▊         | 62/747 [00:13<02:31,  4.52it/s]

Batches:   8%|▊         | 63/747 [00:13<02:28,  4.59it/s]

Batches:   9%|▊         | 64/747 [00:13<02:24,  4.74it/s]

Batches:   9%|▊         | 65/747 [00:13<02:24,  4.71it/s]

Batches:   9%|▉         | 66/747 [00:13<02:24,  4.70it/s]

Batches:   9%|▉         | 67/747 [00:14<02:26,  4.64it/s]

Batches:   9%|▉         | 68/747 [00:14<02:28,  4.58it/s]

Batches:   9%|▉         | 69/747 [00:14<02:27,  4.60it/s]

Batches:   9%|▉         | 70/747 [00:14<02:24,  4.69it/s]

Batches:  10%|▉         | 71/747 [00:15<02:20,  4.80it/s]

Batches:  10%|▉         | 72/747 [00:15<02:16,  4.94it/s]

Batches:  10%|▉         | 73/747 [00:15<02:15,  4.99it/s]

Batches:  10%|▉         | 74/747 [00:15<02:15,  4.96it/s]

Batches:  10%|█         | 75/747 [00:15<02:12,  5.08it/s]

Batches:  10%|█         | 76/747 [00:16<02:10,  5.14it/s]

Batches:  10%|█         | 77/747 [00:16<02:14,  4.97it/s]

Batches:  10%|█         | 78/747 [00:16<02:14,  4.96it/s]

Batches:  11%|█         | 79/747 [00:16<02:14,  4.98it/s]

Batches:  11%|█         | 80/747 [00:16<02:12,  5.04it/s]

Batches:  11%|█         | 81/747 [00:17<02:13,  5.00it/s]

Batches:  11%|█         | 82/747 [00:17<02:12,  5.04it/s]

Batches:  11%|█         | 83/747 [00:17<02:15,  4.90it/s]

Batches:  11%|█         | 84/747 [00:17<02:16,  4.85it/s]

Batches:  11%|█▏        | 85/747 [00:17<02:21,  4.70it/s]

Batches:  12%|█▏        | 86/747 [00:18<02:17,  4.82it/s]

Batches:  12%|█▏        | 87/747 [00:18<02:11,  5.00it/s]

Batches:  12%|█▏        | 88/747 [00:18<02:10,  5.05it/s]

Batches:  12%|█▏        | 89/747 [00:18<02:09,  5.09it/s]

Batches:  12%|█▏        | 90/747 [00:18<02:10,  5.04it/s]

Batches:  12%|█▏        | 91/747 [00:19<02:09,  5.05it/s]

Batches:  12%|█▏        | 92/747 [00:19<02:10,  5.03it/s]

Batches:  12%|█▏        | 93/747 [00:19<02:11,  4.99it/s]

Batches:  13%|█▎        | 94/747 [00:19<02:07,  5.13it/s]

Batches:  13%|█▎        | 95/747 [00:19<02:07,  5.12it/s]

Batches:  13%|█▎        | 96/747 [00:20<02:07,  5.12it/s]

Batches:  13%|█▎        | 97/747 [00:20<02:05,  5.16it/s]

Batches:  13%|█▎        | 98/747 [00:20<02:03,  5.23it/s]

Batches:  13%|█▎        | 99/747 [00:20<02:07,  5.08it/s]

Batches:  13%|█▎        | 100/747 [00:20<02:06,  5.10it/s]

Batches:  14%|█▎        | 101/747 [00:20<02:05,  5.15it/s]

Batches:  14%|█▎        | 102/747 [00:21<02:07,  5.06it/s]

Batches:  14%|█▍        | 103/747 [00:21<02:05,  5.14it/s]

Batches:  14%|█▍        | 104/747 [00:21<02:08,  5.01it/s]

Batches:  14%|█▍        | 105/747 [00:21<02:13,  4.82it/s]

Batches:  14%|█▍        | 106/747 [00:22<02:13,  4.78it/s]

Batches:  14%|█▍        | 107/747 [00:22<02:14,  4.76it/s]

Batches:  14%|█▍        | 108/747 [00:22<02:11,  4.85it/s]

Batches:  15%|█▍        | 109/747 [00:22<02:15,  4.72it/s]

Batches:  15%|█▍        | 110/747 [00:22<02:16,  4.66it/s]

Batches:  15%|█▍        | 111/747 [00:23<02:16,  4.67it/s]

Batches:  15%|█▍        | 112/747 [00:23<02:13,  4.77it/s]

Batches:  15%|█▌        | 113/747 [00:23<02:12,  4.78it/s]

Batches:  15%|█▌        | 114/747 [00:23<02:11,  4.82it/s]

Batches:  15%|█▌        | 115/747 [00:23<02:09,  4.89it/s]

Batches:  16%|█▌        | 116/747 [00:24<02:12,  4.75it/s]

Batches:  16%|█▌        | 117/747 [00:24<02:15,  4.64it/s]

Batches:  16%|█▌        | 118/747 [00:24<02:13,  4.72it/s]

Batches:  16%|█▌        | 119/747 [00:24<02:07,  4.91it/s]

Batches:  16%|█▌        | 120/747 [00:24<02:06,  4.96it/s]

Batches:  16%|█▌        | 121/747 [00:25<02:05,  4.99it/s]

Batches:  16%|█▋        | 122/747 [00:25<02:09,  4.81it/s]

Batches:  16%|█▋        | 123/747 [00:25<02:06,  4.91it/s]

Batches:  17%|█▋        | 124/747 [00:25<02:05,  4.98it/s]

Batches:  17%|█▋        | 125/747 [00:25<02:08,  4.83it/s]

Batches:  17%|█▋        | 126/747 [00:26<02:10,  4.77it/s]

Batches:  17%|█▋        | 127/747 [00:26<02:14,  4.61it/s]

Batches:  17%|█▋        | 128/747 [00:26<02:16,  4.55it/s]

Batches:  17%|█▋        | 129/747 [00:26<02:12,  4.65it/s]

Batches:  17%|█▋        | 130/747 [00:27<02:17,  4.50it/s]

Batches:  18%|█▊        | 131/747 [00:27<02:21,  4.36it/s]

Batches:  18%|█▊        | 132/747 [00:27<02:24,  4.25it/s]

Batches:  18%|█▊        | 133/747 [00:27<02:23,  4.27it/s]

Batches:  18%|█▊        | 134/747 [00:28<02:21,  4.34it/s]

Batches:  18%|█▊        | 135/747 [00:28<02:16,  4.49it/s]

Batches:  18%|█▊        | 136/747 [00:28<02:14,  4.54it/s]

Batches:  18%|█▊        | 137/747 [00:28<02:13,  4.58it/s]

Batches:  18%|█▊        | 138/747 [00:28<02:11,  4.65it/s]

Batches:  19%|█▊        | 139/747 [00:29<02:12,  4.58it/s]

Batches:  19%|█▊        | 140/747 [00:29<02:18,  4.40it/s]

Batches:  19%|█▉        | 141/747 [00:29<02:20,  4.30it/s]

Batches:  19%|█▉        | 142/747 [00:29<02:20,  4.31it/s]

Batches:  19%|█▉        | 143/747 [00:30<02:18,  4.35it/s]

Batches:  19%|█▉        | 144/747 [00:30<02:23,  4.20it/s]

Batches:  19%|█▉        | 145/747 [00:30<02:24,  4.16it/s]

Batches:  20%|█▉        | 146/747 [00:30<02:16,  4.39it/s]

Batches:  20%|█▉        | 147/747 [00:30<02:13,  4.49it/s]

Batches:  20%|█▉        | 148/747 [00:31<02:16,  4.39it/s]

Batches:  20%|█▉        | 149/747 [00:31<02:15,  4.41it/s]

Batches:  20%|██        | 150/747 [00:31<02:15,  4.39it/s]

Batches:  20%|██        | 151/747 [00:31<02:14,  4.42it/s]

Batches:  20%|██        | 152/747 [00:32<02:17,  4.33it/s]

Batches:  20%|██        | 153/747 [00:32<02:17,  4.33it/s]

Batches:  21%|██        | 154/747 [00:32<02:13,  4.43it/s]

Batches:  21%|██        | 155/747 [00:32<02:10,  4.52it/s]

Batches:  21%|██        | 156/747 [00:33<02:13,  4.44it/s]

Batches:  21%|██        | 157/747 [00:33<02:12,  4.44it/s]

Batches:  21%|██        | 158/747 [00:33<02:10,  4.51it/s]

Batches:  21%|██▏       | 159/747 [00:33<02:07,  4.61it/s]

Batches:  21%|██▏       | 160/747 [00:33<02:06,  4.64it/s]

Batches:  22%|██▏       | 161/747 [00:34<02:09,  4.53it/s]

Batches:  22%|██▏       | 162/747 [00:34<02:03,  4.75it/s]

Batches:  22%|██▏       | 163/747 [00:34<01:58,  4.93it/s]

Batches:  22%|██▏       | 164/747 [00:34<01:54,  5.11it/s]

Batches:  22%|██▏       | 165/747 [00:34<01:59,  4.88it/s]

Batches:  22%|██▏       | 166/747 [00:35<02:00,  4.82it/s]

Batches:  22%|██▏       | 167/747 [00:35<02:01,  4.79it/s]

Batches:  22%|██▏       | 168/747 [00:35<01:58,  4.88it/s]

Batches:  23%|██▎       | 169/747 [00:35<01:56,  4.94it/s]

Batches:  23%|██▎       | 170/747 [00:35<01:53,  5.09it/s]

Batches:  23%|██▎       | 171/747 [00:36<01:59,  4.84it/s]

Batches:  23%|██▎       | 172/747 [00:36<01:59,  4.79it/s]

Batches:  23%|██▎       | 173/747 [00:36<01:57,  4.88it/s]

Batches:  23%|██▎       | 174/747 [00:36<01:55,  4.97it/s]

Batches:  23%|██▎       | 175/747 [00:36<01:55,  4.95it/s]

Batches:  24%|██▎       | 176/747 [00:37<01:52,  5.09it/s]

Batches:  24%|██▎       | 177/747 [00:37<01:53,  5.02it/s]

Batches:  24%|██▍       | 178/747 [00:37<01:48,  5.22it/s]

Batches:  24%|██▍       | 179/747 [00:37<01:52,  5.07it/s]

Batches:  24%|██▍       | 180/747 [00:37<01:51,  5.06it/s]

Batches:  24%|██▍       | 181/747 [00:38<01:50,  5.13it/s]

Batches:  24%|██▍       | 182/747 [00:38<01:49,  5.17it/s]

Batches:  24%|██▍       | 183/747 [00:38<01:47,  5.27it/s]

Batches:  25%|██▍       | 184/747 [00:38<01:48,  5.20it/s]

Batches:  25%|██▍       | 185/747 [00:38<01:50,  5.11it/s]

Batches:  25%|██▍       | 186/747 [00:39<01:50,  5.08it/s]

Batches:  25%|██▌       | 187/747 [00:39<01:49,  5.11it/s]

Batches:  25%|██▌       | 188/747 [00:39<01:49,  5.12it/s]

Batches:  25%|██▌       | 189/747 [00:39<01:46,  5.22it/s]

Batches:  25%|██▌       | 190/747 [00:39<01:45,  5.29it/s]

Batches:  26%|██▌       | 191/747 [00:39<01:45,  5.27it/s]

Batches:  26%|██▌       | 192/747 [00:40<01:46,  5.20it/s]

Batches:  26%|██▌       | 193/747 [00:40<01:43,  5.37it/s]

Batches:  26%|██▌       | 194/747 [00:40<01:45,  5.24it/s]

Batches:  26%|██▌       | 195/747 [00:40<01:44,  5.30it/s]

Batches:  26%|██▌       | 196/747 [00:40<01:42,  5.37it/s]

Batches:  26%|██▋       | 197/747 [00:41<01:40,  5.47it/s]

Batches:  27%|██▋       | 198/747 [00:41<01:41,  5.40it/s]

Batches:  27%|██▋       | 199/747 [00:41<01:45,  5.20it/s]

Batches:  27%|██▋       | 200/747 [00:41<01:48,  5.05it/s]

Batches:  27%|██▋       | 201/747 [00:41<01:45,  5.17it/s]

Batches:  27%|██▋       | 202/747 [00:42<01:44,  5.21it/s]

Batches:  27%|██▋       | 203/747 [00:42<01:44,  5.21it/s]

Batches:  27%|██▋       | 204/747 [00:42<01:42,  5.28it/s]

Batches:  27%|██▋       | 205/747 [00:42<01:42,  5.28it/s]

Batches:  28%|██▊       | 206/747 [00:42<01:41,  5.31it/s]

Batches:  28%|██▊       | 207/747 [00:43<01:44,  5.16it/s]

Batches:  28%|██▊       | 208/747 [00:43<01:44,  5.14it/s]

Batches:  28%|██▊       | 209/747 [00:43<01:44,  5.16it/s]

Batches:  28%|██▊       | 210/747 [00:43<01:42,  5.22it/s]

Batches:  28%|██▊       | 211/747 [00:43<01:41,  5.29it/s]

Batches:  28%|██▊       | 212/747 [00:44<01:42,  5.23it/s]

Batches:  29%|██▊       | 213/747 [00:44<01:40,  5.33it/s]

Batches:  29%|██▊       | 214/747 [00:44<01:41,  5.23it/s]

Batches:  29%|██▉       | 215/747 [00:44<01:42,  5.17it/s]

Batches:  29%|██▉       | 216/747 [00:44<01:39,  5.33it/s]

Batches:  29%|██▉       | 217/747 [00:44<01:41,  5.23it/s]

Batches:  29%|██▉       | 218/747 [00:45<01:38,  5.39it/s]

Batches:  29%|██▉       | 219/747 [00:45<01:38,  5.35it/s]

Batches:  29%|██▉       | 220/747 [00:45<01:38,  5.35it/s]

Batches:  30%|██▉       | 221/747 [00:45<01:38,  5.32it/s]

Batches:  30%|██▉       | 222/747 [00:45<01:38,  5.31it/s]

Batches:  30%|██▉       | 223/747 [00:46<01:36,  5.42it/s]

Batches:  30%|██▉       | 224/747 [00:46<01:36,  5.42it/s]

Batches:  30%|███       | 225/747 [00:46<01:37,  5.36it/s]

Batches:  30%|███       | 226/747 [00:46<01:37,  5.34it/s]

Batches:  30%|███       | 227/747 [00:46<01:37,  5.34it/s]

Batches:  31%|███       | 228/747 [00:47<01:38,  5.29it/s]

Batches:  31%|███       | 229/747 [00:47<01:38,  5.28it/s]

Batches:  31%|███       | 230/747 [00:47<01:36,  5.34it/s]

Batches:  31%|███       | 231/747 [00:47<01:37,  5.31it/s]

Batches:  31%|███       | 232/747 [00:47<01:38,  5.24it/s]

Batches:  31%|███       | 233/747 [00:47<01:36,  5.30it/s]

Batches:  31%|███▏      | 234/747 [00:48<01:36,  5.33it/s]

Batches:  31%|███▏      | 235/747 [00:48<01:35,  5.39it/s]

Batches:  32%|███▏      | 236/747 [00:48<01:35,  5.32it/s]

Batches:  32%|███▏      | 237/747 [00:48<01:35,  5.33it/s]

Batches:  32%|███▏      | 238/747 [00:48<01:36,  5.27it/s]

Batches:  32%|███▏      | 239/747 [00:49<01:36,  5.25it/s]

Batches:  32%|███▏      | 240/747 [00:49<01:37,  5.22it/s]

Batches:  32%|███▏      | 241/747 [00:49<01:35,  5.33it/s]

Batches:  32%|███▏      | 242/747 [00:49<01:32,  5.43it/s]

Batches:  33%|███▎      | 243/747 [00:49<01:30,  5.56it/s]

Batches:  33%|███▎      | 244/747 [00:49<01:31,  5.48it/s]

Batches:  33%|███▎      | 245/747 [00:50<01:32,  5.44it/s]

Batches:  33%|███▎      | 246/747 [00:50<01:31,  5.45it/s]

Batches:  33%|███▎      | 247/747 [00:50<01:32,  5.41it/s]

Batches:  33%|███▎      | 248/747 [00:50<01:31,  5.48it/s]

Batches:  33%|███▎      | 249/747 [00:50<01:42,  4.87it/s]

Batches:  33%|███▎      | 250/747 [00:51<01:39,  5.02it/s]

Batches:  34%|███▎      | 251/747 [00:51<01:36,  5.15it/s]

Batches:  34%|███▎      | 252/747 [00:51<01:35,  5.19it/s]

Batches:  34%|███▍      | 253/747 [00:51<01:32,  5.35it/s]

Batches:  34%|███▍      | 254/747 [00:51<01:29,  5.52it/s]

Batches:  34%|███▍      | 255/747 [00:52<01:26,  5.66it/s]

Batches:  34%|███▍      | 256/747 [00:52<01:26,  5.66it/s]

Batches:  34%|███▍      | 257/747 [00:52<01:28,  5.54it/s]

Batches:  35%|███▍      | 258/747 [00:52<01:29,  5.46it/s]

Batches:  35%|███▍      | 259/747 [00:52<01:29,  5.47it/s]

Batches:  35%|███▍      | 260/747 [00:52<01:29,  5.45it/s]

Batches:  35%|███▍      | 261/747 [00:53<01:29,  5.45it/s]

Batches:  35%|███▌      | 262/747 [00:53<01:30,  5.38it/s]

Batches:  35%|███▌      | 263/747 [00:53<01:30,  5.37it/s]

Batches:  35%|███▌      | 264/747 [00:53<01:30,  5.34it/s]

Batches:  35%|███▌      | 265/747 [00:53<01:31,  5.26it/s]

Batches:  36%|███▌      | 266/747 [00:54<01:29,  5.37it/s]

Batches:  36%|███▌      | 267/747 [00:54<01:33,  5.12it/s]

Batches:  36%|███▌      | 268/747 [00:54<01:30,  5.27it/s]

Batches:  36%|███▌      | 269/747 [00:54<01:27,  5.47it/s]

Batches:  36%|███▌      | 270/747 [00:54<01:32,  5.18it/s]

Batches:  36%|███▋      | 271/747 [00:55<01:31,  5.20it/s]

Batches:  36%|███▋      | 272/747 [00:55<01:32,  5.15it/s]

Batches:  37%|███▋      | 273/747 [00:55<01:31,  5.17it/s]

Batches:  37%|███▋      | 274/747 [00:55<01:28,  5.35it/s]

Batches:  37%|███▋      | 275/747 [00:55<01:26,  5.46it/s]

Batches:  37%|███▋      | 276/747 [00:55<01:26,  5.48it/s]

Batches:  37%|███▋      | 277/747 [00:56<01:27,  5.37it/s]

Batches:  37%|███▋      | 278/747 [00:56<01:25,  5.47it/s]

Batches:  37%|███▋      | 279/747 [00:56<01:24,  5.53it/s]

Batches:  37%|███▋      | 280/747 [00:56<01:24,  5.51it/s]

Batches:  38%|███▊      | 281/747 [00:56<01:24,  5.49it/s]

Batches:  38%|███▊      | 282/747 [00:57<01:23,  5.54it/s]

Batches:  38%|███▊      | 283/747 [00:57<01:26,  5.35it/s]

Batches:  38%|███▊      | 284/747 [00:57<01:24,  5.45it/s]

Batches:  38%|███▊      | 285/747 [00:57<01:27,  5.31it/s]

Batches:  38%|███▊      | 286/747 [00:57<01:28,  5.22it/s]

Batches:  38%|███▊      | 287/747 [00:58<01:26,  5.32it/s]

Batches:  39%|███▊      | 288/747 [00:58<01:25,  5.35it/s]

Batches:  39%|███▊      | 289/747 [00:58<01:24,  5.44it/s]

Batches:  39%|███▉      | 290/747 [00:58<01:26,  5.31it/s]

Batches:  39%|███▉      | 291/747 [00:58<01:22,  5.50it/s]

Batches:  39%|███▉      | 292/747 [00:58<01:23,  5.47it/s]

Batches:  39%|███▉      | 293/747 [00:59<01:23,  5.42it/s]

Batches:  39%|███▉      | 294/747 [00:59<01:24,  5.34it/s]

Batches:  39%|███▉      | 295/747 [00:59<01:23,  5.42it/s]

Batches:  40%|███▉      | 296/747 [00:59<01:26,  5.18it/s]

Batches:  40%|███▉      | 297/747 [00:59<01:29,  5.00it/s]

Batches:  40%|███▉      | 298/747 [01:00<01:26,  5.21it/s]

Batches:  40%|████      | 299/747 [01:00<01:23,  5.39it/s]

Batches:  40%|████      | 300/747 [01:00<01:23,  5.36it/s]

Batches:  40%|████      | 301/747 [01:00<01:21,  5.46it/s]

Batches:  40%|████      | 302/747 [01:00<01:21,  5.49it/s]

Batches:  41%|████      | 303/747 [01:00<01:18,  5.62it/s]

Batches:  41%|████      | 304/747 [01:01<01:18,  5.67it/s]

Batches:  41%|████      | 305/747 [01:01<01:19,  5.55it/s]

Batches:  41%|████      | 306/747 [01:01<01:19,  5.54it/s]

Batches:  41%|████      | 307/747 [01:01<01:19,  5.56it/s]

Batches:  41%|████      | 308/747 [01:01<01:20,  5.44it/s]

Batches:  41%|████▏     | 309/747 [01:02<01:21,  5.37it/s]

Batches:  41%|████▏     | 310/747 [01:02<01:19,  5.47it/s]

Batches:  42%|████▏     | 311/747 [01:02<01:19,  5.51it/s]

Batches:  42%|████▏     | 312/747 [01:02<01:18,  5.58it/s]

Batches:  42%|████▏     | 313/747 [01:02<01:16,  5.64it/s]

Batches:  42%|████▏     | 314/747 [01:02<01:16,  5.66it/s]

Batches:  42%|████▏     | 315/747 [01:03<01:18,  5.52it/s]

Batches:  42%|████▏     | 316/747 [01:03<01:14,  5.76it/s]

Batches:  42%|████▏     | 317/747 [01:03<01:15,  5.73it/s]

Batches:  43%|████▎     | 318/747 [01:03<01:15,  5.72it/s]

Batches:  43%|████▎     | 319/747 [01:03<01:15,  5.66it/s]

Batches:  43%|████▎     | 320/747 [01:04<01:14,  5.74it/s]

Batches:  43%|████▎     | 321/747 [01:04<01:15,  5.63it/s]

Batches:  43%|████▎     | 322/747 [01:04<01:19,  5.36it/s]

Batches:  43%|████▎     | 323/747 [01:04<01:17,  5.46it/s]

Batches:  43%|████▎     | 324/747 [01:04<01:16,  5.51it/s]

Batches:  44%|████▎     | 325/747 [01:04<01:17,  5.43it/s]

Batches:  44%|████▎     | 326/747 [01:05<01:17,  5.42it/s]

Batches:  44%|████▍     | 327/747 [01:05<01:17,  5.45it/s]

Batches:  44%|████▍     | 328/747 [01:05<01:15,  5.57it/s]

Batches:  44%|████▍     | 329/747 [01:05<01:14,  5.63it/s]

Batches:  44%|████▍     | 330/747 [01:05<01:13,  5.64it/s]

Batches:  44%|████▍     | 331/747 [01:06<01:13,  5.67it/s]

Batches:  44%|████▍     | 332/747 [01:06<01:13,  5.65it/s]

Batches:  45%|████▍     | 333/747 [01:06<01:12,  5.70it/s]

Batches:  45%|████▍     | 334/747 [01:06<01:13,  5.62it/s]

Batches:  45%|████▍     | 335/747 [01:06<01:14,  5.52it/s]

Batches:  45%|████▍     | 336/747 [01:06<01:14,  5.52it/s]

Batches:  45%|████▌     | 337/747 [01:07<01:15,  5.42it/s]

Batches:  45%|████▌     | 338/747 [01:07<01:15,  5.42it/s]

Batches:  45%|████▌     | 339/747 [01:07<01:15,  5.43it/s]

Batches:  46%|████▌     | 340/747 [01:07<01:10,  5.76it/s]

Batches:  46%|████▌     | 341/747 [01:07<01:10,  5.76it/s]

Batches:  46%|████▌     | 342/747 [01:07<01:09,  5.80it/s]

Batches:  46%|████▌     | 343/747 [01:08<01:10,  5.77it/s]

Batches:  46%|████▌     | 344/747 [01:08<01:09,  5.76it/s]

Batches:  46%|████▌     | 345/747 [01:08<01:10,  5.67it/s]

Batches:  46%|████▋     | 346/747 [01:08<01:11,  5.59it/s]

Batches:  46%|████▋     | 347/747 [01:08<01:15,  5.31it/s]

Batches:  47%|████▋     | 348/747 [01:09<01:11,  5.55it/s]

Batches:  47%|████▋     | 349/747 [01:09<01:12,  5.49it/s]

Batches:  47%|████▋     | 350/747 [01:09<01:11,  5.58it/s]

Batches:  47%|████▋     | 351/747 [01:09<01:11,  5.58it/s]

Batches:  47%|████▋     | 352/747 [01:09<01:10,  5.61it/s]

Batches:  47%|████▋     | 353/747 [01:09<01:09,  5.71it/s]

Batches:  47%|████▋     | 354/747 [01:10<01:08,  5.73it/s]

Batches:  48%|████▊     | 355/747 [01:10<01:08,  5.69it/s]

Batches:  48%|████▊     | 356/747 [01:10<01:09,  5.61it/s]

Batches:  48%|████▊     | 357/747 [01:10<01:10,  5.52it/s]

Batches:  48%|████▊     | 358/747 [01:10<01:09,  5.60it/s]

Batches:  48%|████▊     | 359/747 [01:11<01:13,  5.26it/s]

Batches:  48%|████▊     | 360/747 [01:11<01:09,  5.55it/s]

Batches:  48%|████▊     | 361/747 [01:11<01:07,  5.71it/s]

Batches:  48%|████▊     | 362/747 [01:11<01:07,  5.74it/s]

Batches:  49%|████▊     | 363/747 [01:11<01:04,  5.96it/s]

Batches:  49%|████▊     | 364/747 [01:11<01:03,  6.02it/s]

Batches:  49%|████▉     | 365/747 [01:12<01:07,  5.69it/s]

Batches:  49%|████▉     | 366/747 [01:12<01:06,  5.70it/s]

Batches:  49%|████▉     | 367/747 [01:12<01:01,  6.20it/s]

Batches:  49%|████▉     | 368/747 [01:12<01:01,  6.19it/s]

Batches:  49%|████▉     | 369/747 [01:12<00:59,  6.33it/s]

Batches:  50%|████▉     | 370/747 [01:12<00:57,  6.53it/s]

Batches:  50%|████▉     | 371/747 [01:12<00:57,  6.57it/s]

Batches:  50%|████▉     | 372/747 [01:13<00:57,  6.54it/s]

Batches:  50%|████▉     | 373/747 [01:13<01:00,  6.19it/s]

Batches:  50%|█████     | 374/747 [01:13<01:00,  6.11it/s]

Batches:  50%|█████     | 375/747 [01:13<00:59,  6.23it/s]

Batches:  50%|█████     | 376/747 [01:13<01:00,  6.14it/s]

Batches:  50%|█████     | 377/747 [01:13<01:01,  6.04it/s]

Batches:  51%|█████     | 378/747 [01:14<01:02,  5.94it/s]

Batches:  51%|█████     | 379/747 [01:14<01:01,  5.97it/s]

Batches:  51%|█████     | 380/747 [01:14<01:00,  6.03it/s]

Batches:  51%|█████     | 381/747 [01:14<00:57,  6.38it/s]

Batches:  51%|█████     | 382/747 [01:14<00:59,  6.17it/s]

Batches:  51%|█████▏    | 383/747 [01:14<00:59,  6.08it/s]

Batches:  51%|█████▏    | 384/747 [01:15<00:57,  6.33it/s]

Batches:  52%|█████▏    | 385/747 [01:15<01:00,  6.01it/s]

Batches:  52%|█████▏    | 386/747 [01:15<01:01,  5.90it/s]

Batches:  52%|█████▏    | 387/747 [01:15<01:01,  5.83it/s]

Batches:  52%|█████▏    | 388/747 [01:15<01:01,  5.81it/s]

Batches:  52%|█████▏    | 389/747 [01:15<00:57,  6.27it/s]

Batches:  52%|█████▏    | 390/747 [01:16<00:57,  6.22it/s]

Batches:  52%|█████▏    | 391/747 [01:16<00:58,  6.11it/s]

Batches:  52%|█████▏    | 392/747 [01:16<00:58,  6.12it/s]

Batches:  53%|█████▎    | 393/747 [01:16<00:57,  6.16it/s]

Batches:  53%|█████▎    | 394/747 [01:16<00:58,  6.04it/s]

Batches:  53%|█████▎    | 395/747 [01:16<00:58,  6.03it/s]

Batches:  53%|█████▎    | 396/747 [01:17<00:55,  6.32it/s]

Batches:  53%|█████▎    | 397/747 [01:17<00:55,  6.29it/s]

Batches:  53%|█████▎    | 398/747 [01:17<00:53,  6.49it/s]

Batches:  53%|█████▎    | 399/747 [01:17<00:54,  6.43it/s]

Batches:  54%|█████▎    | 400/747 [01:17<00:51,  6.79it/s]

Batches:  54%|█████▎    | 401/747 [01:17<00:50,  6.87it/s]

Batches:  54%|█████▍    | 402/747 [01:17<00:53,  6.48it/s]

Batches:  54%|█████▍    | 403/747 [01:18<00:51,  6.64it/s]

Batches:  54%|█████▍    | 404/747 [01:18<00:51,  6.64it/s]

Batches:  54%|█████▍    | 405/747 [01:18<00:51,  6.65it/s]

Batches:  54%|█████▍    | 406/747 [01:18<00:53,  6.39it/s]

Batches:  54%|█████▍    | 407/747 [01:18<00:54,  6.23it/s]

Batches:  55%|█████▍    | 408/747 [01:18<00:50,  6.69it/s]

Batches:  55%|█████▍    | 409/747 [01:19<00:50,  6.65it/s]

Batches:  55%|█████▍    | 410/747 [01:19<00:50,  6.64it/s]

Batches:  55%|█████▌    | 411/747 [01:19<00:48,  6.95it/s]

Batches:  55%|█████▌    | 412/747 [01:19<00:48,  6.97it/s]

Batches:  55%|█████▌    | 413/747 [01:19<00:45,  7.36it/s]

Batches:  55%|█████▌    | 414/747 [01:19<00:45,  7.36it/s]

Batches:  56%|█████▌    | 415/747 [01:19<00:46,  7.19it/s]

Batches:  56%|█████▌    | 416/747 [01:19<00:45,  7.21it/s]

Batches:  56%|█████▌    | 417/747 [01:20<00:46,  7.05it/s]

Batches:  56%|█████▌    | 418/747 [01:20<00:44,  7.32it/s]

Batches:  56%|█████▌    | 419/747 [01:20<00:48,  6.75it/s]

Batches:  56%|█████▌    | 420/747 [01:20<00:45,  7.19it/s]

Batches:  56%|█████▋    | 421/747 [01:20<00:48,  6.66it/s]

Batches:  56%|█████▋    | 422/747 [01:20<00:48,  6.65it/s]

Batches:  57%|█████▋    | 423/747 [01:20<00:44,  7.30it/s]

Batches:  57%|█████▋    | 424/747 [01:21<00:41,  7.82it/s]

Batches:  57%|█████▋    | 425/747 [01:21<00:40,  8.04it/s]

Batches:  57%|█████▋    | 426/747 [01:21<00:41,  7.68it/s]

Batches:  57%|█████▋    | 427/747 [01:21<00:43,  7.36it/s]

Batches:  57%|█████▋    | 428/747 [01:21<00:41,  7.60it/s]

Batches:  57%|█████▋    | 429/747 [01:21<00:40,  7.82it/s]

Batches:  58%|█████▊    | 430/747 [01:21<00:41,  7.73it/s]

Batches:  58%|█████▊    | 431/747 [01:21<00:39,  7.91it/s]

Batches:  58%|█████▊    | 432/747 [01:22<00:42,  7.50it/s]

Batches:  58%|█████▊    | 433/747 [01:22<00:39,  8.03it/s]

Batches:  58%|█████▊    | 434/747 [01:22<00:38,  8.23it/s]

Batches:  58%|█████▊    | 435/747 [01:22<00:36,  8.51it/s]

Batches:  58%|█████▊    | 436/747 [01:22<00:37,  8.30it/s]

Batches:  59%|█████▊    | 437/747 [01:22<00:38,  8.09it/s]

Batches:  59%|█████▊    | 438/747 [01:22<00:36,  8.46it/s]

Batches:  59%|█████▉    | 439/747 [01:22<00:37,  8.23it/s]

Batches:  59%|█████▉    | 440/747 [01:23<00:37,  8.12it/s]

Batches:  59%|█████▉    | 441/747 [01:23<00:38,  7.93it/s]

Batches:  59%|█████▉    | 442/747 [01:23<00:38,  7.94it/s]

Batches:  59%|█████▉    | 443/747 [01:23<00:37,  8.14it/s]

Batches:  59%|█████▉    | 444/747 [01:23<00:36,  8.22it/s]

Batches:  60%|█████▉    | 445/747 [01:23<00:36,  8.36it/s]

Batches:  60%|█████▉    | 446/747 [01:23<00:41,  7.34it/s]

Batches:  60%|█████▉    | 447/747 [01:24<00:41,  7.18it/s]

Batches:  60%|█████▉    | 448/747 [01:24<00:38,  7.74it/s]

Batches:  60%|██████    | 449/747 [01:24<00:36,  8.25it/s]

Batches:  60%|██████    | 450/747 [01:24<00:37,  7.85it/s]

Batches:  60%|██████    | 451/747 [01:24<00:36,  8.06it/s]

Batches:  61%|██████    | 452/747 [01:24<00:35,  8.30it/s]

Batches:  61%|██████    | 453/747 [01:24<00:34,  8.58it/s]

Batches:  61%|██████    | 454/747 [01:24<00:35,  8.20it/s]

Batches:  61%|██████    | 455/747 [01:24<00:34,  8.47it/s]

Batches:  61%|██████    | 456/747 [01:25<00:34,  8.55it/s]

Batches:  61%|██████    | 457/747 [01:25<00:34,  8.53it/s]

Batches:  61%|██████▏   | 458/747 [01:25<00:33,  8.57it/s]

Batches:  62%|██████▏   | 460/747 [01:25<00:30,  9.35it/s]

Batches:  62%|██████▏   | 462/747 [01:25<00:29,  9.72it/s]

Batches:  62%|██████▏   | 464/747 [01:25<00:28, 10.10it/s]

Batches:  62%|██████▏   | 465/747 [01:25<00:28,  9.93it/s]

Batches:  62%|██████▏   | 466/747 [01:26<00:29,  9.42it/s]

Batches:  63%|██████▎   | 467/747 [01:26<00:31,  9.03it/s]

Batches:  63%|██████▎   | 469/747 [01:26<00:30,  9.19it/s]

Batches:  63%|██████▎   | 471/747 [01:26<00:31,  8.87it/s]

Batches:  63%|██████▎   | 472/747 [01:26<00:33,  8.28it/s]

Batches:  63%|██████▎   | 473/747 [01:26<00:32,  8.48it/s]

Batches:  63%|██████▎   | 474/747 [01:27<00:31,  8.75it/s]

Batches:  64%|██████▎   | 476/747 [01:27<00:28,  9.58it/s]

Batches:  64%|██████▍   | 477/747 [01:27<00:28,  9.62it/s]

Batches:  64%|██████▍   | 478/747 [01:27<00:28,  9.60it/s]

Batches:  64%|██████▍   | 480/747 [01:27<00:27,  9.80it/s]

Batches:  64%|██████▍   | 481/747 [01:27<00:27,  9.55it/s]

Batches:  65%|██████▍   | 483/747 [01:27<00:26,  9.88it/s]

Batches:  65%|██████▍   | 485/747 [01:28<00:26, 10.06it/s]

Batches:  65%|██████▌   | 487/747 [01:28<00:25, 10.19it/s]

Batches:  65%|██████▌   | 489/747 [01:28<00:24, 10.38it/s]

Batches:  66%|██████▌   | 491/747 [01:28<00:23, 10.68it/s]

Batches:  66%|██████▌   | 493/747 [01:28<00:24, 10.44it/s]

Batches:  66%|██████▋   | 495/747 [01:29<00:24, 10.33it/s]

Batches:  67%|██████▋   | 497/747 [01:29<00:24, 10.34it/s]

Batches:  67%|██████▋   | 499/747 [01:29<00:23, 10.38it/s]

Batches:  67%|██████▋   | 501/747 [01:29<00:23, 10.29it/s]

Batches:  67%|██████▋   | 503/747 [01:29<00:23, 10.41it/s]

Batches:  68%|██████▊   | 505/747 [01:30<00:22, 10.63it/s]

Batches:  68%|██████▊   | 507/747 [01:30<00:22, 10.73it/s]

Batches:  68%|██████▊   | 509/747 [01:30<00:22, 10.43it/s]

Batches:  68%|██████▊   | 511/747 [01:30<00:22, 10.44it/s]

Batches:  69%|██████▊   | 513/747 [01:30<00:21, 10.96it/s]

Batches:  69%|██████▉   | 515/747 [01:30<00:20, 11.17it/s]

Batches:  69%|██████▉   | 517/747 [01:31<00:20, 11.13it/s]

Batches:  69%|██████▉   | 519/747 [01:31<00:20, 11.19it/s]

Batches:  70%|██████▉   | 521/747 [01:31<00:20, 10.98it/s]

Batches:  70%|███████   | 523/747 [01:31<00:20, 11.11it/s]

Batches:  70%|███████   | 525/747 [01:31<00:20, 10.85it/s]

Batches:  71%|███████   | 527/747 [01:32<00:21, 10.32it/s]

Batches:  71%|███████   | 529/747 [01:32<00:20, 10.60it/s]

Batches:  71%|███████   | 531/747 [01:32<00:19, 11.22it/s]

Batches:  71%|███████▏  | 533/747 [01:32<00:18, 11.29it/s]

Batches:  72%|███████▏  | 535/747 [01:32<00:18, 11.50it/s]

Batches:  72%|███████▏  | 537/747 [01:32<00:18, 11.38it/s]

Batches:  72%|███████▏  | 539/747 [01:33<00:18, 11.36it/s]

Batches:  72%|███████▏  | 541/747 [01:33<00:17, 11.86it/s]

Batches:  73%|███████▎  | 543/747 [01:33<00:17, 11.81it/s]

Batches:  73%|███████▎  | 545/747 [01:33<00:17, 11.76it/s]

Batches:  73%|███████▎  | 547/747 [01:33<00:16, 12.10it/s]

Batches:  73%|███████▎  | 549/747 [01:33<00:15, 12.65it/s]

Batches:  74%|███████▍  | 551/747 [01:34<00:15, 13.02it/s]

Batches:  74%|███████▍  | 553/747 [01:34<00:14, 13.01it/s]

Batches:  74%|███████▍  | 555/747 [01:34<00:14, 13.06it/s]

Batches:  75%|███████▍  | 557/747 [01:34<00:14, 13.15it/s]

Batches:  75%|███████▍  | 559/747 [01:34<00:14, 12.77it/s]

Batches:  75%|███████▌  | 561/747 [01:34<00:14, 12.59it/s]

Batches:  75%|███████▌  | 563/747 [01:34<00:14, 12.89it/s]

Batches:  76%|███████▌  | 565/747 [01:35<00:13, 13.08it/s]

Batches:  76%|███████▌  | 567/747 [01:35<00:13, 13.00it/s]

Batches:  76%|███████▌  | 569/747 [01:35<00:13, 13.35it/s]

Batches:  76%|███████▋  | 571/747 [01:35<00:12, 13.67it/s]

Batches:  77%|███████▋  | 573/747 [01:35<00:12, 13.76it/s]

Batches:  77%|███████▋  | 575/747 [01:35<00:12, 14.24it/s]

Batches:  77%|███████▋  | 577/747 [01:35<00:11, 14.53it/s]

Batches:  78%|███████▊  | 579/747 [01:36<00:11, 14.08it/s]

Batches:  78%|███████▊  | 581/747 [01:36<00:11, 14.02it/s]

Batches:  78%|███████▊  | 583/747 [01:36<00:11, 13.89it/s]

Batches:  78%|███████▊  | 585/747 [01:36<00:10, 14.75it/s]

Batches:  79%|███████▊  | 587/747 [01:36<00:10, 14.91it/s]

Batches:  79%|███████▉  | 589/747 [01:36<00:10, 14.98it/s]

Batches:  79%|███████▉  | 591/747 [01:36<00:10, 15.02it/s]

Batches:  79%|███████▉  | 593/747 [01:37<00:09, 15.48it/s]

Batches:  80%|███████▉  | 595/747 [01:37<00:09, 15.54it/s]

Batches:  80%|███████▉  | 597/747 [01:37<00:09, 16.39it/s]

Batches:  80%|████████  | 599/747 [01:37<00:09, 15.67it/s]

Batches:  80%|████████  | 601/747 [01:37<00:08, 16.27it/s]

Batches:  81%|████████  | 603/747 [01:37<00:08, 16.30it/s]

Batches:  81%|████████  | 605/747 [01:37<00:09, 15.54it/s]

Batches:  81%|████████▏ | 607/747 [01:37<00:08, 16.21it/s]

Batches:  82%|████████▏ | 609/747 [01:37<00:08, 16.91it/s]

Batches:  82%|████████▏ | 611/747 [01:38<00:07, 17.47it/s]

Batches:  82%|████████▏ | 613/747 [01:38<00:07, 18.04it/s]

Batches:  82%|████████▏ | 615/747 [01:38<00:07, 17.81it/s]

Batches:  83%|████████▎ | 617/747 [01:38<00:07, 17.82it/s]

Batches:  83%|████████▎ | 619/747 [01:38<00:07, 17.83it/s]

Batches:  83%|████████▎ | 621/747 [01:38<00:07, 17.79it/s]

Batches:  83%|████████▎ | 623/747 [01:38<00:06, 17.95it/s]

Batches:  84%|████████▎ | 625/747 [01:38<00:07, 17.03it/s]

Batches:  84%|████████▍ | 627/747 [01:39<00:06, 17.42it/s]

Batches:  84%|████████▍ | 629/747 [01:39<00:06, 17.41it/s]

Batches:  85%|████████▍ | 632/747 [01:39<00:06, 18.45it/s]

Batches:  85%|████████▍ | 634/747 [01:39<00:06, 18.52it/s]

Batches:  85%|████████▌ | 637/747 [01:39<00:05, 19.76it/s]

Batches:  86%|████████▌ | 640/747 [01:39<00:05, 20.11it/s]

Batches:  86%|████████▌ | 643/747 [01:39<00:04, 21.27it/s]

Batches:  86%|████████▋ | 646/747 [01:39<00:04, 21.56it/s]

Batches:  87%|████████▋ | 649/747 [01:40<00:04, 21.70it/s]

Batches:  87%|████████▋ | 652/747 [01:40<00:04, 21.20it/s]

Batches:  88%|████████▊ | 655/747 [01:40<00:04, 21.86it/s]

Batches:  88%|████████▊ | 658/747 [01:40<00:03, 22.99it/s]

Batches:  88%|████████▊ | 661/747 [01:40<00:03, 23.47it/s]

Batches:  89%|████████▉ | 664/747 [01:40<00:03, 23.26it/s]

Batches:  89%|████████▉ | 667/747 [01:40<00:03, 24.20it/s]

Batches:  90%|████████▉ | 670/747 [01:40<00:03, 24.35it/s]

Batches:  90%|█████████ | 673/747 [01:41<00:02, 24.91it/s]

Batches:  90%|█████████ | 676/747 [01:41<00:02, 25.54it/s]

Batches:  91%|█████████ | 679/747 [01:41<00:02, 26.17it/s]

Batches:  91%|█████████▏| 682/747 [01:41<00:02, 26.80it/s]

Batches:  92%|█████████▏| 685/747 [01:41<00:02, 26.13it/s]

Batches:  92%|█████████▏| 689/747 [01:41<00:02, 27.85it/s]

Batches:  93%|█████████▎| 693/747 [01:41<00:01, 29.29it/s]

Batches:  93%|█████████▎| 697/747 [01:41<00:01, 31.07it/s]

Batches:  94%|█████████▍| 701/747 [01:41<00:01, 31.43it/s]

Batches:  94%|█████████▍| 705/747 [01:42<00:01, 32.13it/s]

Batches:  95%|█████████▍| 709/747 [01:42<00:01, 32.90it/s]

Batches:  95%|█████████▌| 713/747 [01:42<00:00, 34.02it/s]

Batches:  96%|█████████▌| 717/747 [01:42<00:00, 34.56it/s]

Batches:  97%|█████████▋| 721/747 [01:42<00:00, 33.83it/s]

Batches:  97%|█████████▋| 725/747 [01:42<00:00, 34.45it/s]

Batches:  98%|█████████▊| 729/747 [01:42<00:00, 35.19it/s]

Batches:  98%|█████████▊| 733/747 [01:42<00:00, 35.52it/s]

Batches:  99%|█████████▊| 737/747 [01:42<00:00, 35.49it/s]

Batches:  99%|█████████▉| 741/747 [01:43<00:00, 35.45it/s]

Batches: 100%|█████████▉| 745/747 [01:43<00:00, 35.54it/s]

Batches: 100%|██████████| 747/747 [01:43<00:00,  7.23it/s]

<All keys matched successfully>

Dev: bge_m3

Dev: qwen3

,run_name,model,mode,dense_weight,bm25_weight,question_count,mrr,complete_evidence_mrr,returned_count,empty_retrieval,...,no_relevant_hit_at_5,no_relevant_hit_at_10,returned_count_at_1,returned_count_at_3,returned_count_at_5,returned_count_at_10,empty_retrieval_rate_at_1,empty_retrieval_rate_at_3,empty_retrieval_rate_at_5,empty_retrieval_rate_at_10
0,bge_base_hybrid_d0.05_b0.95,bge_base,hybrid_d0.05_b0.95,0.05,0.95,162,0.568651,0.568651,10.0,0.0,...,0.160494,0.111111,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
1,gte_modernbert_hybrid_d0.05_b0.95,gte_modernbert,hybrid_d0.05_b0.95,0.05,0.95,162,0.554884,0.554884,10.0,0.0,...,0.160494,0.111111,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
2,bge_m3_hybrid_d0.05_b0.95,bge_m3,hybrid_d0.05_b0.95,0.05,0.95,162,0.563801,0.563029,10.0,0.0,...,0.166667,0.104938,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
3,qwen3_hybrid_d0.05_b0.95,qwen3,hybrid_d0.05_b0.95,0.05,0.95,162,0.563183,0.563183,10.0,0.0,...,0.166667,0.111111,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
4,e5_base_hybrid_d0.05_b0.95,e5_base,hybrid_d0.05_b0.95,0.05,0.95,162,0.553341,0.553341,10.0,0.0,...,0.166667,0.111111,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,e5_base_dense,e5_base,dense,NaN,NaN,162,0.338458,0.338458,10.0,0.0,...,0.432099,0.327160,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
60,gte_modernbert_dense,gte_modernbert,dense,NaN,NaN,162,0.342019,0.341402,10.0,0.0,...,0.438272,0.283951,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
61,jina_dense,jina,dense,NaN,NaN,162,0.328878,0.328878,10.0,0.0,...,0.462963,0.296296,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
62,mpnet_dense,mpnet,dense,NaN,NaN,162,0.301482,0.299939,10.0,0.0,...,0.475309,0.376543,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
63,minilm_dense,minilm,dense,NaN,NaN,162,0.293668,0.291610,10.0,0.0,...,0.500000,0.407407,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0

## 9. Frozen Test run

The Test split is run once with only the frozen BGE-M3 Hybrid configuration
(Dense 0.10 / BM25 0.90). BM25 is not rerun on Test, and no Test-wide model
or weight sweep is present.

In [10]:
def evaluate_test_frozen() -> tuple[list[dict], list[dict]]:
    rows = []
    candidates = []
    hybrid, _ = build_project_retriever(
        FROZEN["model"],
        RetrievalMode.HYBRID,
        dense_weight=FROZEN["dense_weight"],
        bm25_weight=FROZEN["bm25_weight"],
    )
    for question in test_gold:
        result = hybrid.retrieve(question["question"], FINAL_TOP_K)
        rows.append(
            score_one(
                question,
                hit_pairs(result),
                FROZEN["model"],
                FROZEN["mode"],
                FROZEN["bm25_weight"],
                FROZEN["dense_weight"],
            )
        )
        candidates.extend(candidate_rows(question, FROZEN["model"], FROZEN["mode"], result))
    return rows, candidates


if RUN_EXPENSIVE:
    test_rows, test_candidates = evaluate_test_frozen()
    assert len(test_rows) == len(test_gold)
    assert {row["model"] for row in test_rows} == {FROZEN["model"]}
    assert {row["mode"] for row in test_rows} == {FROZEN["mode"]}
    test_summary = sort_summary(summarize(test_rows))
    test_summary.to_csv(RESULT_DIR / "test_frozen_summary.csv", index=False)
    display(test_summary)
else:
    test_rows = test_candidates = []
    print("Frozen BGE-M3 Test run skipped. Set CS30_M6_RUN_MODELS=1 to run it.")

,run_name,model,mode,dense_weight,bm25_weight,question_count,mrr,complete_evidence_mrr,returned_count,empty_retrieval,...,no_relevant_hit_at_5,no_relevant_hit_at_10,returned_count_at_1,returned_count_at_3,returned_count_at_5,returned_count_at_10,empty_retrieval_rate_at_1,empty_retrieval_rate_at_3,empty_retrieval_rate_at_5,empty_retrieval_rate_at_10
0,bge_m3_hybrid_d0.10_b0.90,bge_m3,hybrid_d0.10_b0.90,0.1,0.9,26,0.453526,0.447115,10.0,0.0,...,0.384615,0.307692,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0

## 10. Save manifest and reviewable outputs

In [11]:
def write_jsonl(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "".join(json.dumps(row, ensure_ascii=False, allow_nan=False) + "\n" for row in rows),
        encoding="utf-8",
    )


if RUN_EXPENSIVE:
    write_jsonl(WORK_DIR / "gold_span_bindings.jsonl", binding_rows)
    write_jsonl(WORK_DIR / "dev_metrics.jsonl", dev_rows)
    write_jsonl(WORK_DIR / "dev_candidate_hits.jsonl", dev_candidates)
    write_jsonl(WORK_DIR / "test_frozen_metrics.jsonl", test_rows)
    write_jsonl(WORK_DIR / "test_frozen_candidate_hits.jsonl", test_candidates)

    git_state = capture_git_state(PROJECT_ROOT)
    result_files = [
        RESULT_DIR / "dev_summary.csv",
        RESULT_DIR / "test_frozen_summary.csv",
        RESULT_DIR / "truncation_diagnostics.csv",
    ]
    manifest = {
        "schema_version": "m6-w6-v2-project-retriever-1",
        "created_at_utc": datetime.now(UTC).isoformat(),
        "reportable": False,
        "evaluation_set_version": "m6-v2-working-dev162-test26-2026-10-12",
        "split_policy": "team_working_split_from_gold_labels",
        "dev_question_count": len(dev_gold),
        "test_question_count": len(test_gold),
        "test_configuration_count": 1,
        "test_policy": "single predeclared BGE-M3 Hybrid; BM25 not rerun on Test",
        "test_selection_used": False,
        "frozen_configuration": FROZEN,
        "project_retriever": "cs30.pipeline.build_real_retrieval_deps",
        "rrf_input_top_k": RRF_INPUT_TOP_K,
        "rrf_k": RRF_K,
        "bm25_stopwords": True,
        "git": {
            "commit": git_state.commit,
            "dirty": git_state.dirty,
            "snapshot_sha256": git_state.snapshot_sha256,
        },
        "corpus_version": corpus_manifest["corpus_version"],
        "corpus_hash": corpus_manifest["corpus_hash"],
        "manifest_hash": corpus_manifest["manifest_hash"],
        "chunk_config_hash": corpus_manifest["chunk_config_hash"],
        "gold_sha256": sha256(gold_bytes),
        "binding_sha256": sha256(binding_bytes),
        "models": {
            key: {
                "model": spec["model"],
                "revision": spec["revision"],
                "trust_remote_code": spec["trust_remote_code"],
                "query_instruction": spec["query_instruction"],
                "query_prompt_name": spec["query_prompt_name"],
            }
            for key, spec in MODEL_SPECS.items()
        },
        "result_file_sha256": {path.name: sha256(path.read_bytes()) for path in result_files},
        "limitations": [
            "development corpus",
            "three OpenStax textbooks",
            "Gold annotation status is draft",
            "all current questions are answerable",
        ],
    }
    (RESULT_DIR / "run_manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print("Saved reviewable outputs:", RESULT_DIR)
else:
    print("No measured files written during preflight-only execution.")

Saved reviewable outputs: D:\capstone\cs30-personalised-rag\docs\results\m6_w6_v2

## 11. CSV-generated result tables

These cells never contain copied result numbers. They render the committed CSVs
created by the run above.

In [12]:
def display_csv(name: str) -> None:
    path = RESULT_DIR / name
    if not path.is_file():
        print("Pending measured output:", path)
        return
    frame = pd.read_csv(path)
    with pd.option_context("display.max_rows", None, "display.max_columns", None):
        display(frame)


display_csv("dev_summary.csv")
display_csv("test_frozen_summary.csv")
display_csv("truncation_diagnostics.csv")

,run_name,model,mode,dense_weight,bm25_weight,question_count,mrr,complete_evidence_mrr,returned_count,empty_retrieval,hit_at_1,hit_at_3,hit_at_5,hit_at_10,complete_hit_at_1,complete_hit_at_3,complete_hit_at_5,complete_hit_at_10,evidence_recall_at_1,evidence_recall_at_3,evidence_recall_at_5,evidence_recall_at_10,core_precision_at_1,core_precision_at_3,core_precision_at_5,core_precision_at_10,context_noise_rate_at_1,context_noise_rate_at_3,context_noise_rate_at_5,context_noise_rate_at_10,no_relevant_hit_at_1,no_relevant_hit_at_3,no_relevant_hit_at_5,no_relevant_hit_at_10,returned_count_at_1,returned_count_at_3,returned_count_at_5,returned_count_at_10,empty_retrieval_rate_at_1,empty_retrieval_rate_at_3,empty_retrieval_rate_at_5,empty_retrieval_rate_at_10
0,bge_base_hybrid_d0.05_b0.95,bge_base,hybrid_d0.05_b0.95,0.05,0.95,162,0.568651,0.568651,10.0,0.0,0.358025,0.759259,0.839506,0.888889,0.358025,0.759259,0.839506,0.888889,0.358025,0.759259,0.839506,0.888889,0.358025,0.253086,0.167901,0.088889,0.641975,0.746914,0.832099,0.911111,0.641975,0.240741,0.160494,0.111111,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
1,gte_modernbert_hybrid_d0.05_b0.95,gte_modernbert,hybrid_d0.05_b0.95,0.05,0.95,162,0.554884,0.554884,10.0,0.0,0.339506,0.740741,0.839506,0.888889,0.339506,0.740741,0.839506,0.888889,0.339506,0.740741,0.839506,0.888889,0.339506,0.246914,0.167901,0.088889,0.660494,0.753086,0.832099,0.911111,0.660494,0.259259,0.160494,0.111111,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
2,bge_m3_hybrid_d0.05_b0.95,bge_m3,hybrid_d0.05_b0.95,0.05,0.95,162,0.563801,0.563029,10.0,0.0,0.351852,0.753086,0.833333,0.895062,0.351852,0.753086,0.833333,0.888889,0.351852,0.753086,0.833333,0.891975,0.351852,0.251029,0.166667,0.089506,0.648148,0.748971,0.833333,0.910494,0.648148,0.246914,0.166667,0.104938,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
3,qwen3_hybrid_d0.05_b0.95,qwen3,hybrid_d0.05_b0.95,0.05,0.95,162,0.563183,0.563183,10.0,0.0,0.358025,0.740741,0.833333,0.888889,0.358025,0.740741,0.833333,0.888889,0.358025,0.740741,0.833333,0.888889,0.358025,0.246914,0.166667,0.088889,0.641975,0.753086,0.833333,0.911111,0.641975,0.259259,0.166667,0.111111,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
4,e5_base_hybrid_d0.05_b0.95,e5_base,hybrid_d0.05_b0.95,0.05,0.95,162,0.553341,0.553341,10.0,0.0,0.333333,0.753086,0.833333,0.888889,0.333333,0.753086,0.833333,0.888889,0.333333,0.753086,0.833333,0.888889,0.333333,0.251029,0.166667,0.088889,0.666667,0.748971,0.833333,0.911111,0.666667,0.246914,0.166667,0.111111,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
5,bm25_bm25,bm25,bm25,NaN,NaN,162,0.569388,0.569388,10.0,0.0,0.364198,0.753086,0.827160,0.888889,0.364198,0.753086,0.827160,0.888889,0.364198,0.753086,0.827160,0.888889,0.364198,0.251029,0.165432,0.088889,0.635802,0.748971,0.834568,0.911111,0.635802,0.246914,0.172840,0.111111,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
6,jina_hybrid_d0.05_b0.95,jina,hybrid_d0.05_b0.95,0.05,0.95,162,0.561569,0.561569,10.0,0.0,0.351852,0.759259,0.827160,0.876543,0.351852,0.759259,0.827160,0.876543,0.351852,0.759259,0.827160,0.876543,0.351852,0.253086,0.165432,0.087654,0.648148,0.746914,0.834568,0.912346,0.648148,0.240741,0.172840,0.123457,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
7,bge_base_hybrid_d0.10_b0.90,bge_base,hybrid_d0.10_b0.90,0.10,0.90,162,0.549882,0.549882,10.0,0.0,0.333333,0.734568,0.827160,0.888889,0.333333,0.734568,0.827160,0.888889,0.333333,0.734568,0.827160,0.888889,0.333333,0.244856,0.165432,0.088889,0.666667,0.755144,0.834568,0.911111,0.666667,0.265432,0.172840,0.111111,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
8,e5_base_hybrid_d0.10_b0.90,e5_base,hybrid_d0.10_b0.90,0.10,0.90,162,0.538490,0.538490,10.0,0.0,0.320988,0.734568,0.827160,0.882716,0.320988,0.734568,0.827160,0.882716,0.320988,0.734568,0.827160,0.882716,0.320988,0.244856,0.165432,0.088272,0.679012,0.755144,0.834568,0.911728,0.679012,0.265432,0.172840,0.117284,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
9,nomic_hybrid_d0.05_b0.95,nomic,hybrid_d0.05_b0.95,0.05,0.95,162,0.555139,0.554453,10.0,0.0,0.345679,0.734568,0.820988,0.882716,0.345679,0.734568,0.820988,0.876543,0.345679,0.734568,0.820988,0.879630,0.345679,0.244856,0.164198,0.088272,0.654321,0.755144,0.835802,0.911728,0.654321,0.265432,0.179012,0.117284,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
10,qwen3_hybrid_d0.10_b0.90,qwen3,hybrid_d0.10_b0.90,0.10,0.90,162,0.554274,0.553657,10.0,0.0,0.345679,0.734568,0.820988,0.882716,0.345679,0.734568,0.820988,0.876543,0.345679,0.734568,0.820988,0.879630,0.345679,0.244856,0.164198,0.088272,0.654321,0.755144,0.835802,0.911728,0.654321,0.265432,0.179012,0.117284,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
11,jina_hybrid_d0.10_b0.90,jina,hybrid_d0.10_b0.90,0.10,0.90,162,0.539653,0.538771,10.0,0.0,0.327160,0.734568,0.820988,0.876543,0.327160,0.734568,0.820988,0.870370,0.327160,0.734568,0.820988,0.873457,0.327160,0.244856,0.164198,0.087654,0.672840,0.755144,0.835802,0.912346,0.672840,0.265432,0.179012,0.123457,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
12,gte_modernbert_hybrid_d0.10_b0.90,gte_modernbert,hybrid_d0.10_b0.90,0.10,0.90,162,0.536417,0.535731,10.0,0.0,0.320988,0.722222,0.820988,0.888889,0.320988,0.722222,0.820988,0.882716,0.320988,0.722222,0.820988,0.885802,0.320988,0.240741,0.164198,0.088889,0.679012,0.759259,0.835802,0.911111,0.679012,0.277778,0.179012,0.111111,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
13,bge_m3_hybrid_d0.10_b0.90,bge_m3,hybrid_d0.10_b0.90,0.10,0.90,162,0.556143,0.554600,10.0,0.0,0.345679,0.740741,0.820988,0.901235,0.345679,0.740741,0.814815,0.895062,0.345679,0.740741,0.817901,0.898148,0.345679,0.246914,0.164198,0.090123,0.654321,0.753086,0.835802,0.909877,0.654321,0.259259,0.179012,0.098765,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
14,mpnet_hybrid_d0.05_b0.95,mpnet,hybrid_d0.05_b0.95,0.05,0.95,162,0.547509,0.546823,10.0,0.0,0.339506,0.734568,0.808642,0.895062,0.339506,0.734568,0.808642,0.888889,0.339506,0.734568,0.808642,0.891975,0.339506,0.244856,0.161728,0.089506,0.660494,0.755144,0.838272,0.910494,0.660494,0.265432,0.191358,0.104938,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
15,bge_base_hybrid_d0.20_b0.80,bge_base,hybrid_d0.20_b0.80,0.20,0.80,162,0.539607,0.539607,10.0,0.0,0.320988,0.734568,0.808642,0.888889,0.320988,0.734568,0.808642,0.888889,0.320988,0.734568,0.808642,0.888889,0.320988,0.244856,0.161728,0.088889,0.679012,0.755144,0.838272,0.911111,0.679012,0.265432,0.191358,0.111111,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
16,bge_base_hybrid_d0.25_b0.75,bge_base,hybrid_d0.25_b0.75,0.25,0.75,162,0.532971,0.532971,10.0,0.0,0.320988,0.734568,0.808642,0.882716,0.320988,0.734568,0.808642,0.882716,0.320988,0.734568,0.808642,0.882716,0.320988,0.244856,0.161728,0.088272,0.679012,0.755144,0.838272,0.911728,0.679012,0.265432,0.191358,0.117284,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
17,minilm_hybrid_d0.05_b0.95,minilm,hybrid_d0.05_b0.95,0.05,0.95,162,0.545221,0.545221,10.0,0.0,0.345679,0.716049,0.802469,0.882716,0.345679,0.716049,0.802469,0.882716,0.345679,0.716049,0.802469,0.882716,0.345679,0.238683,0.160494,0.088272,0.654321,0.761317,0.839506,0.911728,0.654321,0.283951,0.197531,0.117284,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
18,nomic_hybrid_d0.10_b0.90,nomic,hybrid_d0.10_b0.90,0.10,0.90,162,0.541860,0.540831,10.0,0.0,0.333333,0.722222,0.802469,0.882716,0.333333,0.722222,0.802469,0.876543,0.333333,0.722222,0.802469,0.879630,0.333333,0.240741,0.160494,0.088272,0.666667,0.759259,0.839506,0.911728,0.666667,0.277778,0.197531,0.117284,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
19,gte_modernbert_hybrid_d0.25_b0.75,gte_modernbert,hybrid_d0.25_b0.75,0.25,0.75,162,0.528956,0.527721,10.0,0.0,0.327160,0.685185,0.808642,0.895062,0.327160,0.685185,0.802469,0.888889,0.327160,0.685185,0.805556,0.891975,0.327160,0.228395,0.161728,0.089506,0.672840,0.771605,0.838272,0.910494,0.672840,0.314815,0.191358,0.104938,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
20,bge_m3_hybrid_d0.20_b0.80,bge_m3,hybrid_d0.20_b0.80,0.20,0.80,162,0.552501,0.546328,10.0,0.0,0.351852,0.728395,0.802469,0.882716,0.345679,0.722222,0.796296,0.876543,0.348765,0.725309,0.799383,0.879630,0.351852,0.242798,0.160494,0.088272,0.648148,0.757202,0.839506,0.911728,0.648148,0.271605,0.197531,0.117284,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
21,bge_m3_hybrid_d0.25_b0.75,bge_m3,hybrid_d0.25_b0.75,0.25,0.75,162,0.542889,0.536716,10.0,0.0,0.333333,0.734568,0.802469,0.882716,0.327160,0.728395,0.796296,0.876543,0.330247,0.731481,0.799383,0.879630,0.333333,0.244856,0.160494,0.088272,0.666667,0.755144,0.839506,0.911728,0.666667,0.265432,0.197531,0.117284,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
22,gte_modernbert_hybrid_d0.20_b0.80,gte_modernbert,hybrid_d0.20_b0.80,0.20,0.80,162,0.536398,0.535163,10.0,0.0,0.333333,0.697531,0.802469,0.901235,0.333333,0.697531,0.796296,0.895062,0.333333,0.697531,0.799383,0.898148,0.333333,0.232510,0.160494,0.090123,0.666667,0.767490,0.839506,0.909877,0.666667,0.302469,0.197531,0.098765,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
23,qwen3_hybrid_d0.20_b0.80,qwen3,hybrid_d0.20_b0.80,0.20,0.80,162,0.547127,0.546245,10.0,0.0,0.351852,0.728395,0.783951,0.864198,0.351852,0.728395,0.783951,0.858025,0.351852,0.728395,0.783951,0.861111,0.351852,0.242798,0.156790,0.086420,0.648148,0.757202,0.843210,0.913580,0.648148,0.271605,0.216049,0.135802,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
24,qwen3_hybrid_d0.25_b0.75,qwen3,hybrid_d0.25_b0.75,0.25,0.75,162,0.546490,0.545608,10.0,0.0,0.358025,0.709877,0.783951,0.864198,0.358025,0.709877,0.783951,0.858025,0.358025,0.709877,0.783951,0.861111,0.358025,0.236626,0.156790,0.086420,0.641975,0.763374,0.843210,0.913580,0.641975,0.290123,0.216049,0.135802,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
25,qwen3_hybrid_d0.50_b0.50,qwen3,hybrid_d0.50_b0.50,0.50,0.50,162,0.512309,0.510251,10.0,0.0,0.308642,0.691358,0.790123,0.858025,0.308642,0.685185,0.783951,0.851852,0.308642,0.688272,0.787037,0.854938,0.308642,0.230453,0.158025,0.085802,0.691358,0.769547,0.841975,0.914198,0.691358,0.308642,0.209877,0.141975,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
26,jina_hybrid_d0.20_b0.80,jina,hybrid_d0.20_b0.80,0.20,0.80,162,0.531082,0.527996,10.0,0.0,0.327160,0.703704,0.783951,0.870370,0.327160,0.697531,0.777778,0.864198,0.327160,0.700617,0.780864,0.867284,0.327160,0.234568,0.156790,0.087037,0.672840,0.765432,0.843210,0.912963,0.672840,0.296296,0.216049,0.129630,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
27,jina_hybrid_d0.25_b0.75,jina,hybrid_d0.25_b0.75,0.25,0.75,162,0.524755,0.518582,10.0,0.0,0.320988,0.703704,0.783951,0.864198,0.314815,0.697531,0.777778,0.858025,0.317901,0.700617,0.780864,0.861111,0.320988,0.234568,0.156790,0.086420,0.679012,0.765432,0.843210,0.913580,0.679012,0.296296,0.216049,0.135802,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
28,e5_base_hybrid_d0.20_b0.80,e5_base,hybrid_d0.20_b0.80,0.20,0.80,162,0.518203,0.518203,10.0,0.0,0.314815,0.691358,0.771605,0.876543,0.314815,0.691358,0.771605,0.876543,0.314815,0.691358,0.771605,0.876543,0.314815,0.230453,0.154321,0.087654,0.685185,0.769547,0.845679,0.912346,0.685185,0.308642,0.228395,0.123457,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
29,bge_m3_hybrid_d0.50_b0.50,bge_m3,hybrid_d0.50_b0.50,0.50,0.50,162,0.491507,0.488421,10.0,0.0,0.283951,0.672840,0.777778,0.864198,0.283951,0.666667,0.771605,0.858025,0.283951,0.669753,0.774691,0.861111,0.283951,0.224280,0.155556,0.086420,0.716049,0.775720,0.844444,0.913580,0.716049,0.327160,0.222222,0.135802,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
30,bge_base_hybrid_d0.50_b0.50,bge_base,hybrid_d0.50_b0.50,0.50,0.50,162,0.489041,0.489041,10.0,0.0,0.290123,0.648148,0.771605,0.864198,0.290123,0.648148,0.771605,0.864198,0.290123,0.648148,0.771605,0.864198,0.290123,0.216049,0.154321,0.086420,0.709877,0.783951,0.845679,0.913580,0.709877,0.351852,0.228395,0.135802,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
31,mpnet_hybrid_d0.10_b0.90,mpnet,hybrid_d0.10_b0.90,0.10,0.90,162,0.528559,0.527677,10.0,0.0,0.327160,0.697531,0.765432,0.895062,0.327160,0.697531,0.765432,0.888889,0.327160,0.697531,0.765432,0.891975,0.327160,0.232510,0.153086,0.089506,0.672840,0.767490,0.846914,0.910494,0.672840,0.302469,0.234568,0.104938,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
32,e5_base_hybrid_d0.25_b0.75,e5_base,hybrid_d0.25_b0.75,0.25,0.75,162,0.517372,0.517372,10.0,0.0,0.314815,0.685185,0.765432,0.882716,0.314815,0.685185,0.765432,0.882716,0.314815,0.685185,0.765432,0.882716,0.314815,0.228395,0.153086,0.088272,0.685185,0.771605,0.846914,0.911728,0.685185,0.314815,0.234568,0.117284,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
33,minilm_hybrid_d0.10_b0.90,minilm,hybrid_d0.10_b0.90,0.10,0.90,162,0.515055,0.514369,10.0,0.0,0.314815,0.654321,0.765432,0.888889,0.314815,0.654321,0.765432,0.882716,0.314815,0.654321,0.765432,0.885802,0.314815,0.218107,0.153086,0.088889,0.685185,0.781893,0.846914,0.911111,0.685185,0.345679,0.234568,0.111111,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
34,nomic_hybrid_d0.25_b0.75,nomic,hybrid_d0.25_b0.75,0.25,0.75,162,0.519758,0.518523,10.0,0.0,0.314815,0.691358,0.765432,0.870370,0.314815,0.691358,0.759259,0.864198,0.314815,0.691358,0.762346,0.867284,0.314815,0.230453,0.153086,0.087037,0.685185,0.769547,0.846914,0.912963,0.685185,0.308642,0.234568,0.129630,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
35,nomic_hybrid_d0.20_b0.80,nomic,hybrid_d0.20_b0.80,0.20,0.80,162,0.524978,0.523743,10.0,0.0,0.320988,0.703704,0.759259,0.870370,0.320988,0.703704,0.753086,0.864198,0.320988,0.703704,0.756173,0.867284,0.320988,0.234568,0.151852,0.087037,0.679012,0.765432,0.848148,0.912963,0.679012,0.296296,0.240741,0.129630,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
36,e5_base_hybrid_d0.50_b0.50,e5_base,hybrid_d0.50_b0.50,0.50,0.50,162,0.488058,0.488058,10.0,0.0,0.302469,0.623457,0.753086,0.870370,0.302469,0.623457,0.753086,0.870370,0.302469,0.623457,0.753086,0.870370,0.302469,0.207819,0.150617,0.087037,0.697531,0.792181,0.849383,0.912963,0.697531,0.376543,0.246914,0.129630,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
37,gte_modernbert_hybrid_d0.50_b0.50,gte_modernbert,hybrid_d0.50_b0.50,0.50,0.50,162,0.486268,0.484725,10.0,0.0,0.277778,0.635802,0.759259,0.888889,0.277778,0.635802,0.753086,0.882716,0.277778,0.635802,0.756173,0.885802,0.277778,0.211934,0.151852,0.088889,0.722222,0.788066,0.848148,0.911111,0.722222,0.364198,0.240741,0.111111,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
38,nomic_hybrid_d0.50_b0.50,nomic,hybrid_d0.50_b0.50,0.50,0.50,162,0.489685,0.488450,10.0,0.0,0.308642,0.611111,0.753086,0.858025,0.308642,0.611111,0.746914,0.851852,0.308642,0.611111,0.750000,0.854938,0.308642,0.203704,0.150617,0.085802,0.691358,0.796296,0.849383,0.914198,0.691358,0.388889,0.246914,0.141975,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
39,bge_m3_hybrid_d0.75_b0.25,bge_m3,hybrid_d0.75_b0.25,0.75,0.25,162,0.427442,0.424356,10.0,0.0,0.209877,0.580247,0.753086,0.833333,0.209877,0.574074,0.746914,0.827160,0.209877,0.577160,0.750000,0.830247,0.209877,0.193416,0.150617,0.083333,0.790123,0.806584,0.849383,0.916667,0.790123,0.419753,0.246914,0.166667,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
40,qwen3_hybrid_d0.75_b0.25,qwen3,hybrid_d0.75_b0.25,0.75,0.25,162,0.467081,0.463994,10.0,0.0,0.265432,0.617284,0.746914,0.839506,0.265432,0.611111,0.740741,0.833333,0.265432,0.614198,0.743827,0.836420,0.265432,0.205761,0.149383,0.083951,0.734568,0.794239,0.850617,0.916049,0.734568,0.382716,0.253086,0.160494,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
41,jina_hybrid_d0.50_b0.50,jina,hybrid_d0.50_b0.50,0.50,0.50,162,0.484693,0.481606,10.0,0.0,0.296296,0.592593,0.740741,0.858025,0.296296,0.586420,0.734568,0.851852,0.296296,0.589506,0.737654,0.854938,0.296296,0.197531,0.148148,0.085802,0.703704,0.802469,0.851852,0.914198,0.703704,0.407407,0.259259,0.141975,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
42,mpnet_hybrid_d0.20_b0.80,mpnet,hybrid_d0.20_b0.80,0.20,0.80,162,0.503277,0.502249,10.0,0.0,0.308642,0.654321,0.722222,0.876543,0.308642,0.654321,0.722222,0.870370,0.308642,0.654321,0.722222,0.873457,0.308642,0.218107,0.144444,0.087654,0.691358,0.781893,0.855556,0.912346,0.691358,0.345679,0.277778,0.123457,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
43,mpnet_hybrid_d0.25_b0.75,mpnet,hybrid_d0.25_b0.75,0.25,0.75,162,0.497063,0.496034,10.0,0.0,0.308642,0.635802,0.722222,0.876543,0.308642,0.635802,0.722222,0.870370,0.308642,0.635802,0.722222,0.873457,0.308642,0.211934,0.144444,0.087654,0.691358,0.788066,0.855556,0.912346,0.691358,0.364198,0.277778,0.123457,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
44,gte_modernbert_hybrid_d0.75_b0.25,gte_modernbert,hybrid_d0.75_b0.25,0.75,0.25,162,0.414602,0.413058,10.0,0.0,0.216049,0.537037,0.728395,0.814815,0.216049,0.537037,0.722222,0.808642,0.216049,0.537037,0.725309,0.811728,0.216049,0.179012,0.145679,0.081481,0.783951,0.820988,0.854321,0.918519,0.783951,0.462963,0.271605,0.185185,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
45,mpnet_hybrid_d0.50_b0.50,mpnet,hybrid_d0.50_b0.50,0.50,0.50,162,0.462831,0.459744,10.0,0.0,0.271605,0.580247,0.716049,0.858025,0.271605,0.574074,0.709877,0.851852,0.271605,0.577160,0.712963,0.854938,0.271605,0.193416,0.143210,0.085802,0.728395,0.806584,0.856790,0.914198,0.728395,0.419753,0.283951,0.141975,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
46,minilm_hybrid_d0.25_b0.75,minilm,hybrid_d0.25_b0.75,0.25,0.75,162,0.488573,0.487030,10.0,0.0,0.308642,0.598765,0.709877,0.839506,0.308642,0.598765,0.703704,0.833333,0.308642,0.598765,0.706790,0.836420,0.308642,0.199588,0.141975,0.083951,0.691358,0.800412,0.858025,0.916049,0.691358,0.401235,0.290123,0.160494,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
47,minilm_hybrid_d0.20_b0.80,minilm,hybrid_d0.20_b0.80,0.20,0.80,162,0.490182,0.488948,10.0,0.0,0.308642,0.617284,0.703704,0.845679,0.308642,0.617284,0.697531,0.839506,0.308642,0.617284,0.700617,0.842593,0.308642,0.205761,0.140741,0.084568,0.691358,0.794239,0.859259,0.915432,0.691358,0.382716,0.296296,0.154321,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
48,nomic_hybrid_d0.75_b0.25,nomic,hybrid_d0.75_b0.25,0.75,0.25,162,0.406143,0.404086,10.0,0.0,0.185185,0.586420,0.703704,0.771605,0.185185,0.580247,0.697531,0.765432,0.185185,0.583333,0.700617,0.768519,0.185185,0.195473,0.140741,0.077160,0.814815,0.804527,0.859259,0.922840,0.814815,0.413580,0.296296,0.228395,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
49,bge_base_hybrid_d0.75_b0.25,bge_base,hybrid_d0.75_b0.25,0.75,0.25,162,0.408380,0.408380,10.0,0.0,0.185185,0.567901,0.691358,0.814815,0.185185,0.567901,0.691358,0.814815,0.185185,0.567901,0.691358,0.814815,0.185185,0.189300,0.138272,0.081481,0.814815,0.810700,0.861728,0.918519,0.814815,0.432099,0.308642,0.185185,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
50,e5_base_hybrid_d0.75_b0.25,e5_base,hybrid_d0.75_b0.25,0.75,0.25,162,0.403792,0.403792,10.0,0.0,0.197531,0.543210,0.672840,0.790123,0.197531,0.543210,0.672840,0.790123,0.197531,0.543210,0.672840,0.790123,0.197531,0.181070,0.134568,0.079012,0.802469,0.818930,0.865432,0.920988,0.802469,0.456790,0.327160,0.209877,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
51,bge_m3_dense,bge_m3,dense,NaN,NaN,162,0.395451,0.393908,10.0,0.0,0.197531,0.530864,0.679012,0.765432,0.197531,0.530864,0.672840,0.759259,0.197531,0.530864,0.675926,0.762346,0.197531,0.176955,0.135802,0.076543,0.802469,0.823045,0.864198,0.923457,0.802469,0.469136,0.320988,0.234568,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
52,jina_hybrid_d0.75_b0.25,jina,hybrid_d0.75_b0.25,0.75,0.25,162,0.390256,0.387169,10.0,0.0,0.179012,0.530864,0.672840,0.783951,0.179012,0.524691,0.666667,0.777778,0.179012,0.527778,0.669753,0.780864,0.179012,0.176955,0.134568,0.078395,0.820988,0.823045,0.865432,0.921605,0.820988,0.469136,0.327160,0.216049,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
53,minilm_hybrid_d0.50_b0.50,minilm,hybrid_d0.50_b0.50,0.50,0.50,162,0.441679,0.435506,10.0,0.0,0.265432,0.543210,0.666667,0.802469,0.259259,0.537037,0.660494,0.796296,0.262346,0.540123,0.663580,0.799383,0.265432,0.181070,0.133333,0.080247,0.734568,0.818930,0.866667,0.919753,0.734568,0.456790,0.333333,0.197531,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0
54,qwen3_dense,qwen3,dense,NaN,NaN,162,0.413842,0.413842,10.0,0.0,0.240741,0.524691,0.648148,0.783951,0.240741,0.524691,0.648148,0.783951,0.240741,0.524691,0.648148,0.783951,0.240741,0.174897,0.129630,0.078395,0.759259,0.825103,0.870370,0.921605,0.759259,0.475309,0.351852,0.216049,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0

,run_name,model,mode,dense_weight,bm25_weight,question_count,mrr,complete_evidence_mrr,returned_count,empty_retrieval,hit_at_1,hit_at_3,hit_at_5,hit_at_10,complete_hit_at_1,complete_hit_at_3,complete_hit_at_5,complete_hit_at_10,evidence_recall_at_1,evidence_recall_at_3,evidence_recall_at_5,evidence_recall_at_10,core_precision_at_1,core_precision_at_3,core_precision_at_5,core_precision_at_10,context_noise_rate_at_1,context_noise_rate_at_3,context_noise_rate_at_5,context_noise_rate_at_10,no_relevant_hit_at_1,no_relevant_hit_at_3,no_relevant_hit_at_5,no_relevant_hit_at_10,returned_count_at_1,returned_count_at_3,returned_count_at_5,returned_count_at_10,empty_retrieval_rate_at_1,empty_retrieval_rate_at_3,empty_retrieval_rate_at_5,empty_retrieval_rate_at_10
0,bge_m3_hybrid_d0.10_b0.90,bge_m3,hybrid_d0.10_b0.90,0.1,0.9,26,0.453526,0.447115,10.0,0.0,0.307692,0.615385,0.615385,0.692308,0.307692,0.615385,0.615385,0.653846,0.307692,0.615385,0.615385,0.673077,0.307692,0.205128,0.123077,0.069231,0.692308,0.794872,0.876923,0.930769,0.692308,0.384615,0.384615,0.307692,1.0,3.0,5.0,10.0,0.0,0.0,0.0,0.0

,model,embedding_model,embedding_revision,max_input_tokens,maximum_observed_tokens,chunk_count,truncated_chunk_count,truncated_chunk_rate
0,minilm,sentence-transformers/all-MiniLM-L6-v2,1110a243fdf4706b3f48f1d95db1a4f5529b4d41,256,697,5976,3742,0.626171
1,mpnet,sentence-transformers/all-mpnet-base-v2,e8c3b32edf5434bc2275fc9bab85f82640a19130,384,697,5976,2873,0.480756
2,e5_base,intfloat/e5-base-v2,f52bf8ec8c7124536f0efb74aca902b2995e5bcd,512,699,5976,943,0.157798
3,bge_base,BAAI/bge-base-en-v1.5,a5beb1e3e68b9ab74eb54cfd186867f64f240e1a,512,697,5976,885,0.148092
4,jina,jinaai/jina-embeddings-v2-small-en,44e7d1d6caec8c883c2d4b207588504d519788d0,8192,697,5976,0,0.000000
5,gte_modernbert,Alibaba-NLP/gte-modernbert-base,e7f32e3c00f91d699e8c43b53106206bcc72bb22,8192,806,5976,0,0.000000
6,nomic,nomic-ai/nomic-embed-text-v1.5,e9b6763023c676ca8431644204f50c2b100d9aab,8192,701,5976,0,0.000000
7,bge_m3,BAAI/bge-m3,5617a9f61b028005a4858fdac845db406aefb181,8192,828,5976,0,0.000000
8,qwen3,Qwen/Qwen3-Embedding-0.6B,97b0c614be4d77ee51c0cef4e5f07c00f9eb65b3,32768,992,5976,0,0.000000

## Interpretation guardrails

- This is a three-textbook development evaluation, not the formal six-textbook W6 gate.
- The current Gold rows are answerable-only and retain their source annotation status.
- BM25 remains a Dev baseline and is not rerun on Test. The frozen BGE-M3 Hybrid
  configuration is the only Test run; Test results must not be used to retune weights.
- The next PR may add oralized-query, cross-encoder reranking, lexical-overlap bias,
  and refusal-threshold experiments only after their hypotheses are registered in the
  ablation plan.